-- Final batch: remaining question options

-- dp2 options
INSERT INTO public.question_options (id, question_id, text, value, display_order) VALUES
('dp2-1', 'dp2', 'Limit federal role; primary responsibility at state/local level.', 10, 1),
('dp2-2', 'dp2', 'States lead; federal aid when events exceed state capacity.', 5, 2),
('dp2-3', 'dp2', 'Yes for major disasters; build state capacity and pre‑disaster mitigation.', 0, 3),
('dp2-4', 'dp2', 'Yes—FEMA leadership with state/local partners.', -5, 4),
('dp2-5', 'dp2', 'Yes—strong federal leadership and climate resilience.', -10, 5),
('dp7-1', 'dp7', 'Yes—shift security to private sector and local control.', 10, 1),
('dp7-2', 'dp7', 'Consider privatization with strong oversight.', 5, 2),
('dp7-3', 'dp7', 'Pilot privatized screening in some airports with strict standards.', 0, 3),
('dp7-4', 'dp7', 'No—maintain TSA with oversight and innovation.', -5, 4),
('dp7-5', 'dp7', 'No—keep public, improve civil‑liberties protections.', -10, 5),
('dp8-1', 'dp8', 'Reduce or eliminate NEA/NEH.', 10, 1),
('dp8-2', 'dp8', 'Hold flat or reduce; encourage private philanthropy.', 5, 2),
('dp8-3', 'dp8', 'Modest increases tied to access/education outcomes.', 0, 3),
('dp8-4', 'dp8', 'Yes—grow arts and humanities access nationwide.', -5, 4),
('dp8-5', 'dp8', 'Yes—significantly increase NEA/NEH funding.', -10, 5),
('dp10-1', 'dp10', 'Oppose federal eminent domain beyond narrow constitutional uses.', 10, 1),
('dp10-2', 'dp10', 'Restrict use; defend property rights; avoid takings for private gain.', 5, 2),
('dp10-3', 'dp10', 'Case‑by‑case; protect property rights and due process.', 0, 3),
('dp10-4', 'dp10', 'Allow for true public use with fair compensation and safeguards.', -5, 4),
('dp10-5', 'dp10', 'Use sparingly with strong community consent; no for private pipelines.', -10, 5),
('dp12-1', 'dp12', 'Oppose federal micromanagement of agriculture.', 10, 1),
('dp12-2', 'dp12', 'Caution on new mandates; rely on states and existing laws.', 5, 2),
('dp12-3', 'dp12', 'Targeted standards and transparency; support farmers in transition.', 0, 3),
('dp12-4', 'dp12', 'Yes—toughen environmental and animal‑welfare standards.', -5, 4),
('dp12-5', 'dp12', 'Yes—strong federal rules and shift toward sustainable farming.', -10, 5),
('dp13-1', 'dp13', 'Oppose federal involvement in zoning.', 10, 1),
('dp13-2', 'dp13', 'No heavy federal role; leave zoning to states/localities.', 5, 2),
('dp13-3', 'dp13', 'Offer incentives and model codes; keep local input.', 0, 3),
('dp13-4', 'dp13', 'Yes—use incentives and fair‑housing rules to open up housing supply.', -5, 4),
('dp13-5', 'dp13', 'Yes—tie federal funds to fair housing and inclusive zoning.', -10, 5),
('dp15-1', 'dp15', 'No—reduce federal taxes and return power to states.', 10, 1),
('dp15-2', 'dp15', 'Oppose increases; reprioritize spending and cut waste.', 5, 2),
('dp15-3', 'dp15', 'Consider indexing or mileage fees with offsets.', 0, 3),
('dp15-4', 'dp15', 'Yes—modest increase/indexing to maintain infrastructure.', -5, 4),
('dp15-5', 'dp15', 'Yes—raise and index to fund climate‑friendly infrastructure.', -10, 5),
('dp17-1', 'dp17', 'Strongly oppose; protect free speech from federal control.', 10, 1),
('dp17-2', 'dp17', 'No—government shouldn''t police viewpoints.', 5, 2),
('dp17-3', 'dp17', 'Prefer transparency rules over content mandates.', 0, 3),
('dp17-4', 'dp17', 'Consider updates to promote transparency and fair access.', -5, 4),
('dp17-5', 'dp17', 'Yes—promote viewpoint diversity and curb corporate media power.', -10, 5),
-- Immigration
('imm3-1', 'imm3', 'Oppose pathway; enforce current law.', 10, 1),
('imm3-2', 'imm3', 'Earned legalization after border security.', 5, 2),
('imm3-3', 'imm3', 'Yes—with requirements and enforcement.', 0, 3),
('imm3-4', 'imm3', 'Yes—humane pathway with requirements.', -5, 4),
('imm3-5', 'imm3', 'Yes—broad pathway with minimal barriers.', -10, 5),
('immi4-1', 'immi4', 'Decrease—tight caps and strict vetting.', 10, 1),
('immi4-2', 'immi4', 'Hold steady or reduce; prioritize enforcement and assimilation.', 5, 2),
('immi4-3', 'immi4', 'Adjust levels to labor market needs and integration capacity.', 0, 3),
('immi4-4', 'immi4', 'Modestly increase with fair rules and strong worker protections.', -5, 4),
('immi4-5', 'immi4', 'Increase—expand family reunification and humanitarian admissions.', -10, 5),
('immi5-1', 'immi5', 'Yes—merit-based only; reduce family categories.', 10, 1),
('immi5-2', 'immi5', 'Yes—prioritize merit/skills heavily.', 5, 2),
('immi5-3', 'immi5', 'Balance both; weight merit and family.', 0, 3),
('immi5-4', 'immi5', 'Prioritize family reunification; add skills pathway.', -5, 4),
('immi5-5', 'immi5', 'Keep family unity central; protect workers'' rights.', -10, 5),
('immi7-1', 'immi7', 'Yes—broad bans for high-risk regions.', 10, 1),
('immi7-2', 'immi7', 'Yes—temporary restrictions where credible threats exist.', 5, 2),
('immi7-3', 'immi7', 'Use targeted, evidence-based screening lists—not blanket nationality bans.', 0, 3),
('immi7-4', 'immi7', 'No blanket bans; strengthen targeted vetting and intelligence sharing.', -5, 4),
('immi7-5', 'immi7', 'No—oppose blanket bans; use individualized vetting.', -10, 5),
('immi9-1', 'immi9', 'Reduce H-1B and tighten eligibility.', 10, 1),
('immi9-2', 'immi9', 'Increase or streamline H-1B aligned to industry needs; strengthen enforcement.', 5, 2),
('immi9-3', 'immi9', 'Adjust caps to market demand; speed green cards for U.S.-educated STEM grads.', 0, 3),
('immi9-4', 'immi9', 'Increase H-1B with strong wage/anti-abuse rules.', -5, 4),
('immi9-5', 'immi9', 'Protect U.S. and immigrant workers; prevent abuse; focus on green cards over temp visas.', -10, 5),
-- Foreign Policy
('fp1-1', 'fp1', 'Broader executive latitude to respond rapidly to threats.', 10, 1),
('fp1-2', 'fp1', 'Allow limited strikes under existing authorities for national security.', 5, 2),
('fp1-3', 'fp1', 'Allow only brief emergency action pending swift congressional vote.', 0, 3),
('fp1-4', 'fp1', 'Limit unilateral action; restore congressional war powers.', -5, 4),
('fp1-5', 'fp1', 'No—require Congress except for true imminent self‑defense.', -10, 5),
('fp5-1', 'fp5', 'Strong forward posture to defend U.S. interests.', 10, 1),
('fp5-2', 'fp5', 'Increase presence and exercises with allies.', 5, 2),
('fp5-3', 'fp5', 'Shift forces to Indo‑Pacific for deterrence while avoiding escalation.', 0, 3),
('fp5-4', 'fp5', 'Maintain/increase presence to deter aggression with allies.', -5, 4),
('fp5-5', 'fp5', 'Decrease presence; rely on diplomacy and trade.', -10, 5),
('fp9-1', 'fp9', 'Strongly increase and rebuild U.S. military power.', 10, 1),
('fp9-2', 'fp9', 'Increase to deter adversaries and modernize forces.', 5, 2),
('fp9-3', 'fp9', 'Keep spending aligned to strategy; invest in deterrence and efficiency.', 0, 3),
('fp9-4', 'fp9', 'Maintain/target increases for readiness and modern threats; cut waste.', -5, 4),
('fp9-5', 'fp9', 'Decrease and shift funds to domestic priorities.', -10, 5),
('fp10-1', 'fp10', 'Strong executive latitude to defend the nation swiftly.', 10, 1),
('fp10-2', 'fp10', 'Allow limited strikes for national security; notify Congress.', 5, 2),
('fp10-3', 'fp10', 'Emergency defense only; seek rapid authorization for sustained action.', 0, 3),
('fp10-4', 'fp10', 'Limit unilateral action; follow War Powers with timely authorization.', -5, 4),
('fp10-5', 'fp10', 'No—require Congressional authorization except immediate self‑defense.', -10, 5),
('fp12-1', 'fp12', 'Strong, comprehensive sanctions and pressure campaign.', 10, 1),
('fp12-2', 'fp12', 'Increase sanctions to counter malign activity and deter nuclear ambitions.', 5, 2),
('fp12-3', 'fp12', 'Sanction specific violations; keep channels for negotiation.', 0, 3),
('fp12-4', 'fp12', 'Use targeted sanctions tied to diplomacy and nonproliferation.', -5, 4),
('fp12-5', 'fp12', 'Prefer diplomacy and nuclear agreements over broader sanctions.', -10, 5),
('fp19-1', 'fp19', 'Increase readiness and capabilities as needed.', 10, 1),
('fp19-2', 'fp19', 'Modernize for safety/reliability; seek reciprocal reductions.', 5, 2),
('fp19-3', 'fp19', 'Maintain credible deterrent; reduce stockpiles with verifiable treaties.', 0, 3),
('fp19-4', 'fp19', 'Maintain credible deterrent; reduce stockpiles with verifiable treaties.', -5, 4),
('fp19-5', 'fp19', 'Decrease and pursue multilateral disarmament.', -10, 5),
('fp21-1', 'fp21', 'Oppose expanding NATO; avoid provoking Russia.', 10, 1),
('fp21-2', 'fp21', 'Support eventual membership and robust aid now.', 5, 2),
('fp21-3', 'fp21', 'Conditional pathway linked to reforms and a stable ceasefire.', 0, 3),
('fp21-4', 'fp21', 'Support Ukraine''s path to NATO when criteria and conditions are met.', -5, 4),
('fp21-5', 'fp21', 'No—pursue neutrality and negotiated security guarantees.', -10, 5),
('fp25-1', 'fp25', 'Reevaluate commitments; prioritize U.S. sovereignty.', 10, 1),
('fp25-2', 'fp25', 'Strengthen NATO and deterrence while enforcing 2% spending goals.', 5, 2),
('fp25-3', 'fp25', 'Maintain; tie commitments to clear goals and allied spending.', 0, 3),
('fp25-4', 'fp25', 'Maintain/strengthen NATO and push allies on burden‑sharing.', -5, 4),
('fp25-5', 'fp25', 'Decrease U.S. role; emphasize diplomacy and burden shifts.', -10, 5),
-- China/Taiwan
('ct3-1', 'ct3', 'Limit sales; avoid entangling the U.S. in regional wars.', 10, 1),
('ct3-2', 'ct3', 'Yes—accelerate arms to ensure credible deterrence.', 5, 2),
('ct3-3', 'ct3', 'Yes—defensive weapons and training while keeping diplomatic channels open.', 0, 3),
('ct3-4', 'ct3', 'Yes—defensive arms with alliance coordination and crisis management.', -5, 4),
('ct3-5', 'ct3', 'No—prioritize diplomacy and de‑escalation.', -10, 5),
('ct6-1', 'ct6', 'Decrease—avoid foreign entanglements.', 10, 1),
('ct6-2', 'ct6', 'Increase to counter Chinese aggression.', 5, 2),
('ct6-3', 'ct6', 'Maintain presence while prioritizing crisis de‑escalation.', 0, 3),
('ct6-4', 'ct6', 'Maintain or slightly increase for deterrence with allies.', -5, 4),
('ct6-5', 'ct6', 'Decrease; avoid militarization.', -10, 5),
('ct7-1', 'ct7', 'Be cautious—prioritize U.S. interests; avoid entangling measures.', 10, 1),
('ct7-2', 'ct7', 'Yes—strong sanctions to deter abuses.', 5, 2),
('ct7-3', 'ct7', 'Yes—narrow, clearly‑defined sanctions with review.', 0, 3),
('ct7-4', 'ct7', 'Yes—targeted, multilateral sanctions.', -5, 4),
('ct7-5', 'ct7', 'Use targeted sanctions but avoid broad measures that hurt civilians.', -10, 5),
-- Israel/Palestine
('ip1-1', 'ip1', 'Strong unconditional support for Israel.', 10, 1),
('ip1-2', 'ip1', 'Yes—maintain alliance with accountability.', 5, 2),
('ip1-3', 'ip1', 'Continue with oversight and conditions.', 0, 3),
('ip1-4', 'ip1', 'Yes with human rights conditions.', -5, 4),
('ip1-5', 'ip1', 'Reduce or condition on peace progress.', -10, 5),
('ip2-1', 'ip2', 'Oppose; support Israel''s security approach.', 10, 1),
('ip2-2', 'ip2', 'Yes through direct Israel-Palestine negotiations.', 5, 2),
('ip2-3', 'ip2', 'Yes—with security guarantees for both.', 0, 3),
('ip2-4', 'ip2', 'Yes—actively pursue two-state solution.', -5, 4),
('ip2-5', 'ip2', 'Yes—with strong pressure for implementation.', -10, 5),
('ip4-1', 'ip4', 'No conditions on aid.', 10, 1),
('ip4-2', 'ip4', 'Minimal conditions; trust Israel.', 5, 2),
('ip4-3', 'ip4', 'Yes—balanced oversight.', 0, 3),
('ip4-4', 'ip4', 'Yes—condition on human rights.', -5, 4),
('ip4-5', 'ip4', 'Yes—strong human rights conditions.', -10, 5)
ON CONFLICT (id) DO NOTHING;