-- Insert Civil Rights and Liberties questions (10 questions, maps to 'civil-rights' topic)
INSERT INTO questions (id, topic_id, text, is_onboarding_canonical, onboarding_slot) VALUES
  ('crl01', 'civil-rights', 'Should the federal government expand protections against discrimination?', false, null),
  ('crl02', 'civil-rights', 'Should hate crime penalties be increased at the federal level?', false, null),
  ('crl03', 'civil-rights', 'Should federal agencies collect more data on racial disparities?', false, null),
  ('crl04', 'civil-rights', 'Should affirmative action be expanded or limited?', false, null),
  ('crl05', 'civil-rights', 'Should voting rights protections be strengthened nationwide?', false, null),
  ('crl06', 'civil-rights', 'Should federal law restrict the use of facial recognition by police?', false, null),
  ('crl07', 'civil-rights', 'Should federal civil rights enforcement be expanded in housing and lending?', false, null),
  ('crl08', 'civil-rights', 'Should the government fund more legal aid for civil rights cases?', false, null),
  ('crl09', 'civil-rights', 'Should protections for LGBTQ+ individuals be codified in federal law?', false, null),
  ('crl10', 'civil-rights', 'Should Congress increase oversight of civil rights violations in prisons?', false, null);

INSERT INTO question_options (id, question_id, text, value, display_order, is_skip_option) VALUES
  ('crl01-opt-1', 'crl01', 'Yes—because stronger protections are needed nationwide.', -10, 1, false),
  ('crl01-opt-2', 'crl01', 'Yes—but focus on clear gaps in law.', -5, 2, false),
  ('crl01-opt-3', 'crl01', 'Neutral—support modest updates where needed.', 0, 3, false),
  ('crl01-opt-4', 'crl01', 'No—but keep current protections.', 5, 4, false),
  ('crl01-opt-5', 'crl01', 'No—because states should decide.', 10, 5, false),
  ('crl01-skip', 'crl01', 'Not important to me', 0, 6, true),
  ('crl02-opt-1', 'crl02', 'Yes—because stronger deterrence is needed.', -10, 1, false),
  ('crl02-opt-2', 'crl02', 'Yes—but target serious offenses only.', -5, 2, false),
  ('crl02-opt-3', 'crl02', 'Neutral—support modest increases.', 0, 3, false),
  ('crl02-opt-4', 'crl02', 'No—but enforce current laws.', 5, 4, false),
  ('crl02-opt-5', 'crl02', 'No—because penalties are already sufficient.', 10, 5, false),
  ('crl02-skip', 'crl02', 'Not important to me', 0, 6, true),
  ('crl03-opt-1', 'crl03', 'Yes—because data is necessary for accountability.', -10, 1, false),
  ('crl03-opt-2', 'crl03', 'Yes—but focus on key agencies.', -5, 2, false),
  ('crl03-opt-3', 'crl03', 'Neutral—collect targeted data only.', 0, 3, false),
  ('crl03-opt-4', 'crl03', 'No—but keep current reporting.', 5, 4, false),
  ('crl03-opt-5', 'crl03', 'No—because data collection is intrusive.', 10, 5, false),
  ('crl03-skip', 'crl03', 'Not important to me', 0, 6, true),
  ('crl04-opt-1', 'crl04', 'Yes—because affirmative action should expand.', -10, 1, false),
  ('crl04-opt-2', 'crl04', 'Yes—but apply with safeguards.', -5, 2, false),
  ('crl04-opt-3', 'crl04', 'Neutral—allow limited, targeted use.', 0, 3, false),
  ('crl04-opt-4', 'crl04', 'No—but keep narrow exceptions.', 5, 4, false),
  ('crl04-opt-5', 'crl04', 'No—because affirmative action should end.', 10, 5, false),
  ('crl04-skip', 'crl04', 'Not important to me', 0, 6, true),
  ('crl05-opt-1', 'crl05', 'Yes—because federal protections must expand.', -10, 1, false),
  ('crl05-opt-2', 'crl05', 'Yes—but keep state flexibility.', -5, 2, false),
  ('crl05-opt-3', 'crl05', 'Neutral—support targeted updates.', 0, 3, false),
  ('crl05-opt-4', 'crl05', 'No—but maintain current standards.', 5, 4, false),
  ('crl05-opt-5', 'crl05', 'No—because states should control elections.', 10, 5, false),
  ('crl05-skip', 'crl05', 'Not important to me', 0, 6, true),
  ('crl06-opt-1', 'crl06', 'Yes—because it should be banned.', -10, 1, false),
  ('crl06-opt-2', 'crl06', 'Yes—but allow narrow, high-risk exceptions.', -5, 2, false),
  ('crl06-opt-3', 'crl06', 'Neutral—permit limited use with warrants.', 0, 3, false),
  ('crl06-opt-4', 'crl06', 'No—but require basic oversight.', 5, 4, false),
  ('crl06-opt-5', 'crl06', 'No—because law enforcement needs tools.', 10, 5, false),
  ('crl06-skip', 'crl06', 'Not important to me', 0, 6, true),
  ('crl07-opt-1', 'crl07', 'Yes—because enforcement should be stronger.', -10, 1, false),
  ('crl07-opt-2', 'crl07', 'Yes—but focus on clear discrimination cases.', -5, 2, false),
  ('crl07-opt-3', 'crl07', 'Neutral—support targeted enforcement.', 0, 3, false),
  ('crl07-opt-4', 'crl07', 'No—but keep current oversight.', 5, 4, false),
  ('crl07-opt-5', 'crl07', 'No—because federal role should shrink.', 10, 5, false),
  ('crl07-skip', 'crl07', 'Not important to me', 0, 6, true),
  ('crl08-opt-1', 'crl08', 'Yes—because access to justice should expand.', -10, 1, false),
  ('crl08-opt-2', 'crl08', 'Yes—but target low-income cases.', -5, 2, false),
  ('crl08-opt-3', 'crl08', 'Neutral—support limited increases.', 0, 3, false),
  ('crl08-opt-4', 'crl08', 'No—but maintain current funding.', 5, 4, false),
  ('crl08-opt-5', 'crl08', 'No—because legal aid should be private.', 10, 5, false),
  ('crl08-skip', 'crl08', 'Not important to me', 0, 6, true),
  ('crl09-opt-1', 'crl09', 'Yes—because comprehensive protections are needed.', -10, 1, false),
  ('crl09-opt-2', 'crl09', 'Yes—but focus on core civil rights areas.', -5, 2, false),
  ('crl09-opt-3', 'crl09', 'Neutral—support targeted protections.', 0, 3, false),
  ('crl09-opt-4', 'crl09', 'No—but keep current rules.', 5, 4, false),
  ('crl09-opt-5', 'crl09', 'No—because states should decide.', 10, 5, false),
  ('crl09-skip', 'crl09', 'Not important to me', 0, 6, true),
  ('crl10-opt-1', 'crl10', 'Yes—because federal oversight is essential.', -10, 1, false),
  ('crl10-opt-2', 'crl10', 'Yes—but focus on severe violations.', -5, 2, false),
  ('crl10-opt-3', 'crl10', 'Neutral—support limited oversight increases.', 0, 3, false),
  ('crl10-opt-4', 'crl10', 'No—but maintain current standards.', 5, 4, false),
  ('crl10-opt-5', 'crl10', 'No—because prisons should be state-led.', 10, 5, false),
  ('crl10-skip', 'crl10', 'Not important to me', 0, 6, true);