-- Insert Arts, Culture, Religion questions (10 questions, maps to 'technology' topic)
INSERT INTO questions (id, topic_id, text, is_onboarding_canonical, onboarding_slot) VALUES
  ('acr01', 'technology', 'Should federal funding for the arts be increased?', false, null),
  ('acr02', 'technology', 'Should public monuments be reviewed for historical context or bias?', false, null),
  ('acr03', 'technology', 'Should federal grants support cultural preservation programs?', false, null),
  ('acr04', 'technology', 'Should religious organizations receive the same public grant access as secular ones?', false, null),
  ('acr05', 'technology', 'Should the government expand funding for museums and libraries?', false, null),
  ('acr06', 'technology', 'Should federal law protect cultural artifacts from commercial sale?', false, null),
  ('acr07', 'technology', 'Should public schools allow more religious expression?', false, null),
  ('acr08', 'technology', 'Should the government sponsor more community arts education programs?', false, null),
  ('acr09', 'technology', 'Should federal arts grants prioritize underserved communities?', false, null),
  ('acr10', 'technology', 'Should the U.S. increase protections for cultural heritage sites?', false, null);

INSERT INTO question_options (id, question_id, text, value, display_order, is_skip_option) VALUES
  ('acr01-opt-1', 'acr01', 'Yes—because arts funding should expand nationally.', -10, 1, false),
  ('acr01-opt-2', 'acr01', 'Yes—but prioritize underserved communities.', -5, 2, false),
  ('acr01-opt-3', 'acr01', 'Neutral—maintain or slightly increase funding.', 0, 3, false),
  ('acr01-opt-4', 'acr01', 'No—but keep limited support.', 5, 4, false),
  ('acr01-opt-5', 'acr01', 'No—because federal arts funding should end.', 10, 5, false),
  ('acr01-skip', 'acr01', 'Not important to me', 0, 6, true),
  ('acr02-opt-1', 'acr02', 'Yes—because public history should be reevaluated.', -10, 1, false),
  ('acr02-opt-2', 'acr02', 'Yes—but use community input for changes.', -5, 2, false),
  ('acr02-opt-3', 'acr02', 'Neutral—review selectively when issues arise.', 0, 3, false),
  ('acr02-opt-4', 'acr02', 'No—but preserve most monuments.', 5, 4, false),
  ('acr02-opt-5', 'acr02', 'No—because monuments should not be changed.', 10, 5, false),
  ('acr02-skip', 'acr02', 'Not important to me', 0, 6, true),
  ('acr03-opt-1', 'acr03', 'Yes—because cultural preservation needs strong support.', -10, 1, false),
  ('acr03-opt-2', 'acr03', 'Yes—but target high-risk preservation.', -5, 2, false),
  ('acr03-opt-3', 'acr03', 'Neutral—support limited preservation grants.', 0, 3, false),
  ('acr03-opt-4', 'acr03', 'No—but allow private funding.', 5, 4, false),
  ('acr03-opt-5', 'acr03', 'No—because federal grants are unnecessary.', 10, 5, false),
  ('acr03-skip', 'acr03', 'Not important to me', 0, 6, true),
  ('acr04-opt-1', 'acr04', 'Yes—because access should be equal.', -10, 1, false),
  ('acr04-opt-2', 'acr04', 'Yes—but require safeguards against discrimination.', -5, 2, false),
  ('acr04-opt-3', 'acr04', 'Neutral—permit access for non-religious services.', 0, 3, false),
  ('acr04-opt-4', 'acr04', 'No—but allow narrow exceptions.', 5, 4, false),
  ('acr04-opt-5', 'acr04', 'No—because religious groups should not receive grants.', 10, 5, false),
  ('acr04-skip', 'acr04', 'Not important to me', 0, 6, true),
  ('acr05-opt-1', 'acr05', 'Yes—because cultural access should expand.', -10, 1, false),
  ('acr05-opt-2', 'acr05', 'Yes—but focus on modernization.', -5, 2, false),
  ('acr05-opt-3', 'acr05', 'Neutral—support modest targeted funding.', 0, 3, false),
  ('acr05-opt-4', 'acr05', 'No—but keep local funding priorities.', 5, 4, false),
  ('acr05-opt-5', 'acr05', 'No—because federal support should shrink.', 10, 5, false),
  ('acr05-skip', 'acr05', 'Not important to me', 0, 6, true),
  ('acr06-opt-1', 'acr06', 'Yes—because heritage should be protected nationally.', -10, 1, false),
  ('acr06-opt-2', 'acr06', 'Yes—but focus on significant artifacts.', -5, 2, false),
  ('acr06-opt-3', 'acr06', 'Neutral—protect only high-value heritage items.', 0, 3, false),
  ('acr06-opt-4', 'acr06', 'No—but allow voluntary protections.', 5, 4, false),
  ('acr06-opt-5', 'acr06', 'No—because regulation should be minimal.', 10, 5, false),
  ('acr06-skip', 'acr06', 'Not important to me', 0, 6, true),
  ('acr07-opt-1', 'acr07', 'No—but allow private, non-endorsed expression.', -10, 1, false),
  ('acr07-opt-2', 'acr07', 'No—but permit limited voluntary expression.', -5, 2, false),
  ('acr07-opt-3', 'acr07', 'Neutral—balance free expression and neutrality.', 0, 3, false),
  ('acr07-opt-4', 'acr07', 'Yes—but avoid official endorsement.', 5, 4, false),
  ('acr07-opt-5', 'acr07', 'Yes—because schools should allow more expression.', 10, 5, false),
  ('acr07-skip', 'acr07', 'Not important to me', 0, 6, true),
  ('acr08-opt-1', 'acr08', 'Yes—because arts education should be widely supported.', -10, 1, false),
  ('acr08-opt-2', 'acr08', 'Yes—but focus on underserved schools.', -5, 2, false),
  ('acr08-opt-3', 'acr08', 'Neutral—support targeted arts programs.', 0, 3, false),
  ('acr08-opt-4', 'acr08', 'No—but allow local control.', 5, 4, false),
  ('acr08-opt-5', 'acr08', 'No—because federal role should be minimal.', 10, 5, false),
  ('acr08-skip', 'acr08', 'Not important to me', 0, 6, true),
  ('acr09-opt-1', 'acr09', 'Yes—because equity should guide funding.', -10, 1, false),
  ('acr09-opt-2', 'acr09', 'Yes—but maintain some broad access.', -5, 2, false),
  ('acr09-opt-3', 'acr09', 'Neutral—balance equity and merit.', 0, 3, false),
  ('acr09-opt-4', 'acr09', 'No—but keep grants open to all.', 5, 4, false),
  ('acr09-opt-5', 'acr09', 'No—because targeted priorities are unfair.', 10, 5, false),
  ('acr09-skip', 'acr09', 'Not important to me', 0, 6, true),
  ('acr10-opt-1', 'acr10', 'Yes—because heritage sites need strong safeguards.', -10, 1, false),
  ('acr10-opt-2', 'acr10', 'Yes—but prioritize endangered sites.', -5, 2, false),
  ('acr10-opt-3', 'acr10', 'Neutral—support limited protections.', 0, 3, false),
  ('acr10-opt-4', 'acr10', 'No—but maintain current protections.', 5, 4, false),
  ('acr10-opt-5', 'acr10', 'No—because federal protections should be reduced.', 10, 5, false),
  ('acr10-skip', 'acr10', 'Not important to me', 0, 6, true);