-- Set remaining onboarding questions by updating existing questions
UPDATE questions SET is_onboarding_canonical = true, onboarding_slot = 3 WHERE id = 't01';
UPDATE questions SET is_onboarding_canonical = true, onboarding_slot = 6 WHERE id = 'ia04';
UPDATE questions SET is_onboarding_canonical = true, onboarding_slot = 8 WHERE id = 'gop02';
UPDATE questions SET is_onboarding_canonical = true, onboarding_slot = 9 WHERE id = 'cle08';

-- Insert missing Energy questions (using 'eng' prefix to avoid collision with Education 'e')
INSERT INTO questions (id, topic_id, text, is_onboarding_canonical, onboarding_slot) VALUES
('eng01', 'energy', 'Should the federal government expand renewable energy subsidies?', true, 5),
('eng02', 'energy', 'Should the U.S. prioritize renewable energy development over fossil fuel production?', false, null),
('eng03', 'energy', 'Should there be a federal carbon tax on fossil fuel emissions?', false, null),
('eng04', 'energy', 'Should the government subsidize nuclear power plant construction?', false, null),
('eng05', 'energy', 'Should oil and gas drilling be banned on federal lands?', false, null),
('eng06', 'energy', 'Should the government mandate electric vehicle adoption by a certain date?', false, null),
('eng07', 'energy', 'Should energy companies be required to disclose climate-related financial risks?', false, null),
('eng08', 'energy', 'Should the U.S. rejoin and strengthen commitments to international climate agreements?', false, null),
('eng09', 'energy', 'Should fracking be banned or more strictly regulated?', false, null),
('eng10', 'energy', 'Should the government invest in grid modernization and energy storage?', false, null);

-- Insert missing Congress questions (using 'cong' prefix to avoid collision with Commerce 'c')
INSERT INTO questions (id, topic_id, text, is_onboarding_canonical, onboarding_slot) VALUES
('cong01', 'congress', 'Should the Senate limit the use of the filibuster?', true, 8),
('cong02', 'congress', 'Should Congress impose term limits on its members?', false, null),
('cong03', 'congress', 'Should congressional redistricting be done by independent commissions?', false, null),
('cong04', 'congress', 'Should members of Congress be prohibited from trading individual stocks?', false, null),
('cong05', 'congress', 'Should Congress require more transparency in its proceedings?', false, null),
('cong06', 'congress', 'Should congressional salaries be tied to performance or attendance?', false, null),
('cong07', 'congress', 'Should the House of Representatives be expanded?', false, null),
('cong08', 'congress', 'Should earmarks in legislation be banned?', false, null),
('cong09', 'congress', 'Should Congress pass a balanced budget amendment?', false, null),
('cong10', 'congress', 'Should there be stricter ethics enforcement for members of Congress?', false, null);

-- Update gop02 to remove onboarding flag since cong01 now covers filibuster
UPDATE questions SET is_onboarding_canonical = false, onboarding_slot = null WHERE id = 'gop02';

-- Insert options for Energy questions
INSERT INTO question_options (id, question_id, text, value, display_order, is_skip_option) VALUES
('eng01-a', 'eng01', 'Strongly support renewable subsidies', -10, 0, false),
('eng01-b', 'eng01', 'Support some renewable investment', -5, 1, false),
('eng01-c', 'eng01', 'Neutral', 0, 2, false),
('eng01-d', 'eng01', 'Oppose renewable subsidies', 5, 3, false),
('eng01-e', 'eng01', 'Strongly oppose government energy subsidies', 10, 4, false),
('eng01-skip', 'eng01', 'Not important to me', 0, 5, true),
('eng02-a', 'eng02', 'Strongly support prioritizing renewables', -10, 0, false),
('eng02-b', 'eng02', 'Support gradual transition to renewables', -5, 1, false),
('eng02-c', 'eng02', 'Neutral', 0, 2, false),
('eng02-d', 'eng02', 'Support balanced energy approach', 5, 3, false),
('eng02-e', 'eng02', 'Strongly support fossil fuel development', 10, 4, false),
('eng02-skip', 'eng02', 'Not important to me', 0, 5, true),
('eng03-a', 'eng03', 'Strongly support carbon taxation', -10, 0, false),
('eng03-b', 'eng03', 'Support modest carbon pricing', -5, 1, false),
('eng03-c', 'eng03', 'Neutral', 0, 2, false),
('eng03-d', 'eng03', 'Oppose carbon taxes', 5, 3, false),
('eng03-e', 'eng03', 'Strongly oppose any carbon pricing', 10, 4, false),
('eng03-skip', 'eng03', 'Not important to me', 0, 5, true),
('eng04-a', 'eng04', 'Strongly support nuclear subsidies', -10, 0, false),
('eng04-b', 'eng04', 'Support some nuclear investment', -5, 1, false),
('eng04-c', 'eng04', 'Neutral', 0, 2, false),
('eng04-d', 'eng04', 'Oppose nuclear subsidies', 5, 3, false),
('eng04-e', 'eng04', 'Strongly oppose nuclear power expansion', 10, 4, false),
('eng04-skip', 'eng04', 'Not important to me', 0, 5, true),
('eng05-a', 'eng05', 'Strongly support drilling ban', -10, 0, false),
('eng05-b', 'eng05', 'Support restricting new leases', -5, 1, false),
('eng05-c', 'eng05', 'Neutral', 0, 2, false),
('eng05-d', 'eng05', 'Oppose drilling restrictions', 5, 3, false),
('eng05-e', 'eng05', 'Strongly oppose any drilling limits', 10, 4, false),
('eng05-skip', 'eng05', 'Not important to me', 0, 5, true),
('eng06-a', 'eng06', 'Strongly support EV mandates', -10, 0, false),
('eng06-b', 'eng06', 'Support EV incentives and gradual requirements', -5, 1, false),
('eng06-c', 'eng06', 'Neutral', 0, 2, false),
('eng06-d', 'eng06', 'Oppose EV mandates', 5, 3, false),
('eng06-e', 'eng06', 'Strongly oppose government vehicle requirements', 10, 4, false),
('eng06-skip', 'eng06', 'Not important to me', 0, 5, true),
('eng07-a', 'eng07', 'Strongly support mandatory disclosure', -10, 0, false),
('eng07-b', 'eng07', 'Support disclosure requirements', -5, 1, false),
('eng07-c', 'eng07', 'Neutral', 0, 2, false),
('eng07-d', 'eng07', 'Oppose mandatory disclosure', 5, 3, false),
('eng07-e', 'eng07', 'Strongly oppose climate risk reporting', 10, 4, false),
('eng07-skip', 'eng07', 'Not important to me', 0, 5, true),
('eng08-a', 'eng08', 'Strongly support international climate commitments', -10, 0, false),
('eng08-b', 'eng08', 'Support participation with flexibility', -5, 1, false),
('eng08-c', 'eng08', 'Neutral', 0, 2, false),
('eng08-d', 'eng08', 'Oppose binding international agreements', 5, 3, false),
('eng08-e', 'eng08', 'Strongly oppose international climate treaties', 10, 4, false),
('eng08-skip', 'eng08', 'Not important to me', 0, 5, true),
('eng09-a', 'eng09', 'Strongly support fracking ban', -10, 0, false),
('eng09-b', 'eng09', 'Support stricter fracking regulations', -5, 1, false),
('eng09-c', 'eng09', 'Neutral', 0, 2, false),
('eng09-d', 'eng09', 'Oppose fracking restrictions', 5, 3, false),
('eng09-e', 'eng09', 'Strongly oppose fracking regulations', 10, 4, false),
('eng09-skip', 'eng09', 'Not important to me', 0, 5, true),
('eng10-a', 'eng10', 'Strongly support grid investment', -10, 0, false),
('eng10-b', 'eng10', 'Support energy infrastructure upgrades', -5, 1, false),
('eng10-c', 'eng10', 'Neutral', 0, 2, false),
('eng10-d', 'eng10', 'Oppose grid spending', 5, 3, false),
('eng10-e', 'eng10', 'Strongly oppose government energy investment', 10, 4, false),
('eng10-skip', 'eng10', 'Not important to me', 0, 5, true);

-- Insert options for Congress questions
INSERT INTO question_options (id, question_id, text, value, display_order, is_skip_option) VALUES
('cong01-a', 'cong01', 'Strongly support limiting filibuster', -10, 0, false),
('cong01-b', 'cong01', 'Support filibuster reform', -5, 1, false),
('cong01-c', 'cong01', 'Neutral', 0, 2, false),
('cong01-d', 'cong01', 'Oppose filibuster changes', 5, 3, false),
('cong01-e', 'cong01', 'Strongly oppose limiting filibuster', 10, 4, false),
('cong01-skip', 'cong01', 'Not important to me', 0, 5, true),
('cong02-a', 'cong02', 'Strongly support term limits', -10, 0, false),
('cong02-b', 'cong02', 'Support some term limits', -5, 1, false),
('cong02-c', 'cong02', 'Neutral', 0, 2, false),
('cong02-d', 'cong02', 'Oppose term limits', 5, 3, false),
('cong02-e', 'cong02', 'Strongly oppose term limits', 10, 4, false),
('cong02-skip', 'cong02', 'Not important to me', 0, 5, true),
('cong03-a', 'cong03', 'Strongly support independent redistricting', -10, 0, false),
('cong03-b', 'cong03', 'Support redistricting reform', -5, 1, false),
('cong03-c', 'cong03', 'Neutral', 0, 2, false),
('cong03-d', 'cong03', 'Oppose redistricting changes', 5, 3, false),
('cong03-e', 'cong03', 'Strongly oppose independent commissions', 10, 4, false),
('cong03-skip', 'cong03', 'Not important to me', 0, 5, true),
('cong04-a', 'cong04', 'Strongly support stock trading ban', -10, 0, false),
('cong04-b', 'cong04', 'Support trading restrictions', -5, 1, false),
('cong04-c', 'cong04', 'Neutral', 0, 2, false),
('cong04-d', 'cong04', 'Oppose trading restrictions', 5, 3, false),
('cong04-e', 'cong04', 'Strongly oppose stock trading limits', 10, 4, false),
('cong04-skip', 'cong04', 'Not important to me', 0, 5, true),
('cong05-a', 'cong05', 'Strongly support congressional transparency', -10, 0, false),
('cong05-b', 'cong05', 'Support more openness', -5, 1, false),
('cong05-c', 'cong05', 'Neutral', 0, 2, false),
('cong05-d', 'cong05', 'Oppose transparency requirements', 5, 3, false),
('cong05-e', 'cong05', 'Strongly oppose additional transparency', 10, 4, false),
('cong05-skip', 'cong05', 'Not important to me', 0, 5, true),
('cong06-a', 'cong06', 'Strongly support performance-based pay', -10, 0, false),
('cong06-b', 'cong06', 'Support salary accountability', -5, 1, false),
('cong06-c', 'cong06', 'Neutral', 0, 2, false),
('cong06-d', 'cong06', 'Oppose changing congressional pay', 5, 3, false),
('cong06-e', 'cong06', 'Strongly oppose performance pay', 10, 4, false),
('cong06-skip', 'cong06', 'Not important to me', 0, 5, true),
('cong07-a', 'cong07', 'Strongly support House expansion', -10, 0, false),
('cong07-b', 'cong07', 'Support adding representatives', -5, 1, false),
('cong07-c', 'cong07', 'Neutral', 0, 2, false),
('cong07-d', 'cong07', 'Oppose House expansion', 5, 3, false),
('cong07-e', 'cong07', 'Strongly oppose changing House size', 10, 4, false),
('cong07-skip', 'cong07', 'Not important to me', 0, 5, true),
('cong08-a', 'cong08', 'Strongly support earmark ban', -10, 0, false),
('cong08-b', 'cong08', 'Support limiting earmarks', -5, 1, false),
('cong08-c', 'cong08', 'Neutral', 0, 2, false),
('cong08-d', 'cong08', 'Oppose earmark restrictions', 5, 3, false),
('cong08-e', 'cong08', 'Strongly support allowing earmarks', 10, 4, false),
('cong08-skip', 'cong08', 'Not important to me', 0, 5, true),
('cong09-a', 'cong09', 'Strongly support balanced budget requirement', -10, 0, false),
('cong09-b', 'cong09', 'Support fiscal discipline', -5, 1, false),
('cong09-c', 'cong09', 'Neutral', 0, 2, false),
('cong09-d', 'cong09', 'Oppose balanced budget mandate', 5, 3, false),
('cong09-e', 'cong09', 'Strongly oppose balanced budget amendment', 10, 4, false),
('cong09-skip', 'cong09', 'Not important to me', 0, 5, true),
('cong10-a', 'cong10', 'Strongly support ethics enforcement', -10, 0, false),
('cong10-b', 'cong10', 'Support stronger ethics rules', -5, 1, false),
('cong10-c', 'cong10', 'Neutral', 0, 2, false),
('cong10-d', 'cong10', 'Oppose additional ethics oversight', 5, 3, false),
('cong10-e', 'cong10', 'Strongly oppose ethics requirements', 10, 4, false),
('cong10-skip', 'cong10', 'Not important to me', 0, 5, true);