-- Insert Congress questions (10 questions, maps to 'government' topic)
INSERT INTO questions (id, topic_id, text, is_onboarding_canonical, onboarding_slot) VALUES
  ('cong01', 'government', 'Should Congress impose term limits on itself?', false, null),
  ('cong02', 'government', 'Should federal campaign finance laws be strengthened?', false, null),
  ('cong03', 'government', 'Should congressional districts be drawn by independent commissions?', false, null),
  ('cong04', 'government', 'Should Congress limit stock trading by its members?', false, null),
  ('cong05', 'government', 'Should the filibuster be reformed or eliminated?', false, null),
  ('cong06', 'government', 'Should congressional salaries be tied to performance metrics?', false, null),
  ('cong07', 'government', 'Should Congress expand transparency in lobbying?', false, null),
  ('cong08', 'government', 'Should federal ethics rules for Congress be strengthened?', false, null),
  ('cong09', 'government', 'Should Congress meet more days per year?', false, null),
  ('cong10', 'government', 'Should the Electoral Count Act be reformed?', false, null);

INSERT INTO question_options (id, question_id, text, value, display_order, is_skip_option) VALUES
  ('cong01-opt-1', 'cong01', 'Yes—because term limits should be strict.', -10, 1, false),
  ('cong01-opt-2', 'cong01', 'Yes—but allow reasonable terms.', -5, 2, false),
  ('cong01-opt-3', 'cong01', 'Neutral—consider limits with flexibility.', 0, 3, false),
  ('cong01-opt-4', 'cong01', 'No—but encourage voluntary limits.', 5, 4, false),
  ('cong01-opt-5', 'cong01', 'No—because voters should decide.', 10, 5, false),
  ('cong01-skip', 'cong01', 'Not important to me', 0, 6, true),
  ('cong02-opt-1', 'cong02', 'Yes—because money in politics should be limited.', -10, 1, false),
  ('cong02-opt-2', 'cong02', 'Yes—but allow some flexibility.', -5, 2, false),
  ('cong02-opt-3', 'cong02', 'Neutral—support targeted reforms.', 0, 3, false),
  ('cong02-opt-4', 'cong02', 'No—but require transparency.', 5, 4, false),
  ('cong02-opt-5', 'cong02', 'No—because speech should be unrestricted.', 10, 5, false),
  ('cong02-skip', 'cong02', 'Not important to me', 0, 6, true),
  ('cong03-opt-1', 'cong03', 'Yes—because gerrymandering should end.', -10, 1, false),
  ('cong03-opt-2', 'cong03', 'Yes—but allow state input.', -5, 2, false),
  ('cong03-opt-3', 'cong03', 'Neutral—support fair redistricting.', 0, 3, false),
  ('cong03-opt-4', 'cong03', 'No—but maintain some oversight.', 5, 4, false),
  ('cong03-opt-5', 'cong03', 'No—because legislatures should draw maps.', 10, 5, false),
  ('cong03-skip', 'cong03', 'Not important to me', 0, 6, true),
  ('cong04-opt-1', 'cong04', 'Yes—because trading should be banned.', -10, 1, false),
  ('cong04-opt-2', 'cong04', 'Yes—but allow blind trusts.', -5, 2, false),
  ('cong04-opt-3', 'cong04', 'Neutral—support targeted limits.', 0, 3, false),
  ('cong04-opt-4', 'cong04', 'No—but require disclosure.', 5, 4, false),
  ('cong04-opt-5', 'cong04', 'No—because members should invest freely.', 10, 5, false),
  ('cong04-skip', 'cong04', 'Not important to me', 0, 6, true),
  ('cong05-opt-1', 'cong05', 'Yes—because the filibuster should be eliminated.', -10, 1, false),
  ('cong05-opt-2', 'cong05', 'Yes—but reform rather than abolish.', -5, 2, false),
  ('cong05-opt-3', 'cong05', 'Neutral—support modest reforms.', 0, 3, false),
  ('cong05-opt-4', 'cong05', 'No—but keep current rules.', 5, 4, false),
  ('cong05-opt-5', 'cong05', 'No—because the filibuster protects minorities.', 10, 5, false),
  ('cong05-skip', 'cong05', 'Not important to me', 0, 6, true),
  ('cong06-opt-1', 'cong06', 'Yes—because pay should reflect performance.', -10, 1, false),
  ('cong06-opt-2', 'cong06', 'Yes—but use reasonable metrics.', -5, 2, false),
  ('cong06-opt-3', 'cong06', 'Neutral—consider some accountability.', 0, 3, false),
  ('cong06-opt-4', 'cong06', 'No—but maintain current salary rules.', 5, 4, false),
  ('cong06-opt-5', 'cong06', 'No—because salaries should be fixed.', 10, 5, false),
  ('cong06-skip', 'cong06', 'Not important to me', 0, 6, true),
  ('cong07-opt-1', 'cong07', 'Yes—because lobbying should be fully transparent.', -10, 1, false),
  ('cong07-opt-2', 'cong07', 'Yes—but allow reasonable privacy.', -5, 2, false),
  ('cong07-opt-3', 'cong07', 'Neutral—support targeted transparency.', 0, 3, false),
  ('cong07-opt-4', 'cong07', 'No—but keep current rules.', 5, 4, false),
  ('cong07-opt-5', 'cong07', 'No—because lobbying is protected speech.', 10, 5, false),
  ('cong07-skip', 'cong07', 'Not important to me', 0, 6, true),
  ('cong08-opt-1', 'cong08', 'Yes—because ethics rules should be strict.', -10, 1, false),
  ('cong08-opt-2', 'cong08', 'Yes—but allow reasonable exceptions.', -5, 2, false),
  ('cong08-opt-3', 'cong08', 'Neutral—support targeted improvements.', 0, 3, false),
  ('cong08-opt-4', 'cong08', 'No—but maintain current rules.', 5, 4, false),
  ('cong08-opt-5', 'cong08', 'No—because rules are sufficient.', 10, 5, false),
  ('cong08-skip', 'cong08', 'Not important to me', 0, 6, true),
  ('cong09-opt-1', 'cong09', 'Yes—because more time in session is needed.', -10, 1, false),
  ('cong09-opt-2', 'cong09', 'Yes—but balance with district work.', -5, 2, false),
  ('cong09-opt-3', 'cong09', 'Neutral—maintain current schedule.', 0, 3, false),
  ('cong09-opt-4', 'cong09', 'No—but improve efficiency.', 5, 4, false),
  ('cong09-opt-5', 'cong09', 'No—because members need district time.', 10, 5, false),
  ('cong09-skip', 'cong09', 'Not important to me', 0, 6, true),
  ('cong10-opt-1', 'cong10', 'Yes—because reforms are urgently needed.', -10, 1, false),
  ('cong10-opt-2', 'cong10', 'Yes—but keep core procedures.', -5, 2, false),
  ('cong10-opt-3', 'cong10', 'Neutral—support targeted reforms.', 0, 3, false),
  ('cong10-opt-4', 'cong10', 'No—but clarify procedures.', 5, 4, false),
  ('cong10-opt-5', 'cong10', 'No—because the current system works.', 10, 5, false),
  ('cong10-skip', 'cong10', 'Not important to me', 0, 6, true);

-- Insert Crime and Law Enforcement questions (10 questions, maps to 'civil-rights' topic)
INSERT INTO questions (id, topic_id, text, is_onboarding_canonical, onboarding_slot) VALUES
  ('crim01', 'civil-rights', 'Should the federal government increase funding for local police departments?', false, null),
  ('crim02', 'civil-rights', 'Should Congress expand community policing programs?', false, null),
  ('crim03', 'civil-rights', 'Should federal law mandate police training standards?', false, null),
  ('crim04', 'civil-rights', 'Should qualified immunity for police be reformed?', false, null),
  ('crim05', 'civil-rights', 'Should the government increase funding for mental health crisis response?', false, null),
  ('crim06', 'civil-rights', 'Should federal sentencing for drug offenses be reduced?', false, null),
  ('crim07', 'civil-rights', 'Should Congress expand alternatives to incarceration?', false, null),
  ('crim08', 'civil-rights', 'Should the government increase support for prisoner reentry programs?', false, null),
  ('crim09', 'civil-rights', 'Should federal law limit no-knock warrants?', false, null),
  ('crim10', 'civil-rights', 'Should Congress expand resources for prosecuting white-collar crime?', false, null);

INSERT INTO question_options (id, question_id, text, value, display_order, is_skip_option) VALUES
  ('crim01-opt-1', 'crim01', 'No—but shift funds to community programs.', -10, 1, false),
  ('crim01-opt-2', 'crim01', 'No—but maintain current funding.', -5, 2, false),
  ('crim01-opt-3', 'crim01', 'Neutral—balance police and community funding.', 0, 3, false),
  ('crim01-opt-4', 'crim01', 'Yes—but require reforms.', 5, 4, false),
  ('crim01-opt-5', 'crim01', 'Yes—because police need more resources.', 10, 5, false),
  ('crim01-skip', 'crim01', 'Not important to me', 0, 6, true),
  ('crim02-opt-1', 'crim02', 'Yes—because community policing should expand.', -10, 1, false),
  ('crim02-opt-2', 'crim02', 'Yes—but focus on high-need areas.', -5, 2, false),
  ('crim02-opt-3', 'crim02', 'Neutral—support limited programs.', 0, 3, false),
  ('crim02-opt-4', 'crim02', 'No—but maintain current programs.', 5, 4, false),
  ('crim02-opt-5', 'crim02', 'No—because traditional policing is sufficient.', 10, 5, false),
  ('crim02-skip', 'crim02', 'Not important to me', 0, 6, true),
  ('crim03-opt-1', 'crim03', 'Yes—because national standards are needed.', -10, 1, false),
  ('crim03-opt-2', 'crim03', 'Yes—but allow state flexibility.', -5, 2, false),
  ('crim03-opt-3', 'crim03', 'Neutral—support voluntary standards.', 0, 3, false),
  ('crim03-opt-4', 'crim03', 'No—but encourage best practices.', 5, 4, false),
  ('crim03-opt-5', 'crim03', 'No—because states should decide.', 10, 5, false),
  ('crim03-skip', 'crim03', 'Not important to me', 0, 6, true),
  ('crim04-opt-1', 'crim04', 'Yes—because qualified immunity should end.', -10, 1, false),
  ('crim04-opt-2', 'crim04', 'Yes—but narrow rather than abolish.', -5, 2, false),
  ('crim04-opt-3', 'crim04', 'Neutral—support targeted reforms.', 0, 3, false),
  ('crim04-opt-4', 'crim04', 'No—but improve accountability.', 5, 4, false),
  ('crim04-opt-5', 'crim04', 'No—because officers need protection.', 10, 5, false),
  ('crim04-skip', 'crim04', 'Not important to me', 0, 6, true),
  ('crim05-opt-1', 'crim05', 'Yes—because mental health response should expand.', -10, 1, false),
  ('crim05-opt-2', 'crim05', 'Yes—but integrate with existing services.', -5, 2, false),
  ('crim05-opt-3', 'crim05', 'Neutral—support limited expansion.', 0, 3, false),
  ('crim05-opt-4', 'crim05', 'No—but maintain current funding.', 5, 4, false),
  ('crim05-opt-5', 'crim05', 'No—because police should respond.', 10, 5, false),
  ('crim05-skip', 'crim05', 'Not important to me', 0, 6, true),
  ('crim06-opt-1', 'crim06', 'Yes—because drug sentences are too harsh.', -10, 1, false),
  ('crim06-opt-2', 'crim06', 'Yes—but focus on nonviolent offenses.', -5, 2, false),
  ('crim06-opt-3', 'crim06', 'Neutral—support targeted reductions.', 0, 3, false),
  ('crim06-opt-4', 'crim06', 'No—but maintain current sentences.', 5, 4, false),
  ('crim06-opt-5', 'crim06', 'No—because sentences should be tougher.', 10, 5, false),
  ('crim06-skip', 'crim06', 'Not important to me', 0, 6, true),
  ('crim07-opt-1', 'crim07', 'Yes—because alternatives should expand widely.', -10, 1, false),
  ('crim07-opt-2', 'crim07', 'Yes—but focus on low-risk offenders.', -5, 2, false),
  ('crim07-opt-3', 'crim07', 'Neutral—support limited alternatives.', 0, 3, false),
  ('crim07-opt-4', 'crim07', 'No—but keep current options.', 5, 4, false),
  ('crim07-opt-5', 'crim07', 'No—because incarceration is appropriate.', 10, 5, false),
  ('crim07-skip', 'crim07', 'Not important to me', 0, 6, true),
  ('crim08-opt-1', 'crim08', 'Yes—because reentry support should expand.', -10, 1, false),
  ('crim08-opt-2', 'crim08', 'Yes—but focus on high-risk individuals.', -5, 2, false),
  ('crim08-opt-3', 'crim08', 'Neutral—support limited programs.', 0, 3, false),
  ('crim08-opt-4', 'crim08', 'No—but maintain current funding.', 5, 4, false),
  ('crim08-opt-5', 'crim08', 'No—because reentry is an individual responsibility.', 10, 5, false),
  ('crim08-skip', 'crim08', 'Not important to me', 0, 6, true),
  ('crim09-opt-1', 'crim09', 'Yes—because no-knock warrants should be banned.', -10, 1, false),
  ('crim09-opt-2', 'crim09', 'Yes—but allow narrow exceptions.', -5, 2, false),
  ('crim09-opt-3', 'crim09', 'Neutral—support targeted limits.', 0, 3, false),
  ('crim09-opt-4', 'crim09', 'No—but require oversight.', 5, 4, false),
  ('crim09-opt-5', 'crim09', 'No—because police need this tool.', 10, 5, false),
  ('crim09-skip', 'crim09', 'Not important to me', 0, 6, true),
  ('crim10-opt-1', 'crim10', 'Yes—because white-collar crime needs strong enforcement.', -10, 1, false),
  ('crim10-opt-2', 'crim10', 'Yes—but target major offenders.', -5, 2, false),
  ('crim10-opt-3', 'crim10', 'Neutral—support targeted increases.', 0, 3, false),
  ('crim10-opt-4', 'crim10', 'No—but maintain current resources.', 5, 4, false),
  ('crim10-opt-5', 'crim10', 'No—because resources are sufficient.', 10, 5, false),
  ('crim10-skip', 'crim10', 'Not important to me', 0, 6, true);