-- Insert Economics and Public Finance questions (10 questions, maps to 'economy' topic)
INSERT INTO questions (id, topic_id, text, is_onboarding_canonical, onboarding_slot) VALUES
  ('econ01', 'economy', 'Should the federal government run larger deficits to fund programs?', false, null),
  ('econ02', 'economy', 'Should Congress raise the debt ceiling automatically?', false, null),
  ('econ03', 'economy', 'Should the government increase spending on infrastructure?', false, null),
  ('econ04', 'economy', 'Should federal agencies prioritize reducing income inequality?', false, null),
  ('econ05', 'economy', 'Should the government expand unemployment insurance?', false, null),
  ('econ06', 'economy', 'Should Congress cap interest rates on consumer credit?', false, null),
  ('econ07', 'economy', 'Should the government expand housing assistance programs?', false, null),
  ('econ08', 'economy', 'Should federal policy prioritize full employment?', false, null),
  ('econ09', 'economy', 'Should the government invest more in economic development grants?', false, null),
  ('econ10', 'economy', 'Should Congress establish a federal jobs guarantee?', false, null);

INSERT INTO question_options (id, question_id, text, value, display_order, is_skip_option) VALUES
  ('econ01-opt-1', 'econ01', 'Yes—because spending is needed for public good.', -10, 1, false),
  ('econ01-opt-2', 'econ01', 'Yes—but keep deficits manageable.', -5, 2, false),
  ('econ01-opt-3', 'econ01', 'Neutral—balance spending and fiscal prudence.', 0, 3, false),
  ('econ01-opt-4', 'econ01', 'No—but allow limited deficit spending.', 5, 4, false),
  ('econ01-opt-5', 'econ01', 'No—because balanced budgets are essential.', 10, 5, false),
  ('econ01-skip', 'econ01', 'Not important to me', 0, 6, true),
  ('econ02-opt-1', 'econ02', 'Yes—because debt limit brinkmanship is harmful.', -10, 1, false),
  ('econ02-opt-2', 'econ02', 'Yes—but with spending accountability.', -5, 2, false),
  ('econ02-opt-3', 'econ02', 'Neutral—reform the process.', 0, 3, false),
  ('econ02-opt-4', 'econ02', 'No—but avoid defaults.', 5, 4, false),
  ('econ02-opt-5', 'econ02', 'No—because Congress should vote each time.', 10, 5, false),
  ('econ02-skip', 'econ02', 'Not important to me', 0, 6, true),
  ('econ03-opt-1', 'econ03', 'Yes—because infrastructure needs major investment.', -10, 1, false),
  ('econ03-opt-2', 'econ03', 'Yes—but target critical projects.', -5, 2, false),
  ('econ03-opt-3', 'econ03', 'Neutral—support limited increases.', 0, 3, false),
  ('econ03-opt-4', 'econ03', 'No—but maintain current spending.', 5, 4, false),
  ('econ03-opt-5', 'econ03', 'No—because spending should be reduced.', 10, 5, false),
  ('econ03-skip', 'econ03', 'Not important to me', 0, 6, true),
  ('econ04-opt-1', 'econ04', 'Yes—because inequality reduction should be central.', -10, 1, false),
  ('econ04-opt-2', 'econ04', 'Yes—but balance with growth.', -5, 2, false),
  ('econ04-opt-3', 'econ04', 'Neutral—consider inequality among factors.', 0, 3, false),
  ('econ04-opt-4', 'econ04', 'No—but ensure opportunity.', 5, 4, false),
  ('econ04-opt-5', 'econ04', 'No—because markets should determine outcomes.', 10, 5, false),
  ('econ04-skip', 'econ04', 'Not important to me', 0, 6, true),
  ('econ05-opt-1', 'econ05', 'Yes—because benefits should expand.', -10, 1, false),
  ('econ05-opt-2', 'econ05', 'Yes—but target those most in need.', -5, 2, false),
  ('econ05-opt-3', 'econ05', 'Neutral—support modest expansion.', 0, 3, false),
  ('econ05-opt-4', 'econ05', 'No—but maintain current levels.', 5, 4, false),
  ('econ05-opt-5', 'econ05', 'No—because benefits discourage work.', 10, 5, false),
  ('econ05-skip', 'econ05', 'Not important to me', 0, 6, true),
  ('econ06-opt-1', 'econ06', 'Yes—because interest rates are too high.', -10, 1, false),
  ('econ06-opt-2', 'econ06', 'Yes—but allow some flexibility.', -5, 2, false),
  ('econ06-opt-3', 'econ06', 'Neutral—support targeted caps.', 0, 3, false),
  ('econ06-opt-4', 'econ06', 'No—but require transparency.', 5, 4, false),
  ('econ06-opt-5', 'econ06', 'No—because markets should set rates.', 10, 5, false),
  ('econ06-skip', 'econ06', 'Not important to me', 0, 6, true),
  ('econ07-opt-1', 'econ07', 'Yes—because housing assistance should expand.', -10, 1, false),
  ('econ07-opt-2', 'econ07', 'Yes—but target low-income families.', -5, 2, false),
  ('econ07-opt-3', 'econ07', 'Neutral—support limited expansion.', 0, 3, false),
  ('econ07-opt-4', 'econ07', 'No—but maintain current programs.', 5, 4, false),
  ('econ07-opt-5', 'econ07', 'No—because housing should be market-driven.', 10, 5, false),
  ('econ07-skip', 'econ07', 'Not important to me', 0, 6, true),
  ('econ08-opt-1', 'econ08', 'Yes—because full employment should be primary.', -10, 1, false),
  ('econ08-opt-2', 'econ08', 'Yes—but balance with inflation control.', -5, 2, false),
  ('econ08-opt-3', 'econ08', 'Neutral—maintain dual mandate.', 0, 3, false),
  ('econ08-opt-4', 'econ08', 'No—but support employment generally.', 5, 4, false),
  ('econ08-opt-5', 'econ08', 'No—because inflation control is more important.', 10, 5, false),
  ('econ08-skip', 'econ08', 'Not important to me', 0, 6, true),
  ('econ09-opt-1', 'econ09', 'Yes—because development grants should expand.', -10, 1, false),
  ('econ09-opt-2', 'econ09', 'Yes—but target distressed areas.', -5, 2, false),
  ('econ09-opt-3', 'econ09', 'Neutral—support limited increases.', 0, 3, false),
  ('econ09-opt-4', 'econ09', 'No—but maintain current funding.', 5, 4, false),
  ('econ09-opt-5', 'econ09', 'No—because markets should drive development.', 10, 5, false),
  ('econ09-skip', 'econ09', 'Not important to me', 0, 6, true),
  ('econ10-opt-1', 'econ10', 'Yes—because everyone deserves a job.', -10, 1, false),
  ('econ10-opt-2', 'econ10', 'Yes—but as a last resort.', -5, 2, false),
  ('econ10-opt-3', 'econ10', 'Neutral—consider targeted programs.', 0, 3, false),
  ('econ10-opt-4', 'econ10', 'No—but support job training.', 5, 4, false),
  ('econ10-opt-5', 'econ10', 'No—because government jobs distort markets.', 10, 5, false),
  ('econ10-skip', 'econ10', 'Not important to me', 0, 6, true);

-- Insert Education questions (10 questions, maps to 'education' topic)
INSERT INTO questions (id, topic_id, text, is_onboarding_canonical, onboarding_slot) VALUES
  ('educ01', 'education', 'Should the federal government increase funding for public schools?', false, null),
  ('educ02', 'education', 'Should Congress expand student loan forgiveness programs?', false, null),
  ('educ03', 'education', 'Should the government fund universal pre-K?', false, null),
  ('educ04', 'education', 'Should federal law expand school choice options?', false, null),
  ('educ05', 'education', 'Should the government increase Pell Grant funding?', false, null),
  ('educ06', 'education', 'Should Congress limit standardized testing in schools?', false, null),
  ('educ07', 'education', 'Should the government expand vocational training funding?', false, null),
  ('educ08', 'education', 'Should federal policy support teacher pay increases?', false, null),
  ('educ09', 'education', 'Should the government expand support for historically Black colleges?', false, null),
  ('educ10', 'education', 'Should Congress increase funding for special education?', false, null);

INSERT INTO question_options (id, question_id, text, value, display_order, is_skip_option) VALUES
  ('educ01-opt-1', 'educ01', 'Yes—because public education needs strong support.', -10, 1, false),
  ('educ01-opt-2', 'educ01', 'Yes—but target high-need districts.', -5, 2, false),
  ('educ01-opt-3', 'educ01', 'Neutral—support modest increases.', 0, 3, false),
  ('educ01-opt-4', 'educ01', 'No—but maintain current funding.', 5, 4, false),
  ('educ01-opt-5', 'educ01', 'No—because education is a state role.', 10, 5, false),
  ('educ01-skip', 'educ01', 'Not important to me', 0, 6, true),
  ('educ02-opt-1', 'educ02', 'Yes—because student debt should be cancelled.', -10, 1, false),
  ('educ02-opt-2', 'educ02', 'Yes—but target low-income borrowers.', -5, 2, false),
  ('educ02-opt-3', 'educ02', 'Neutral—support limited forgiveness.', 0, 3, false),
  ('educ02-opt-4', 'educ02', 'No—but improve repayment options.', 5, 4, false),
  ('educ02-opt-5', 'educ02', 'No—because borrowers should repay.', 10, 5, false),
  ('educ02-skip', 'educ02', 'Not important to me', 0, 6, true),
  ('educ03-opt-1', 'educ03', 'Yes—because universal pre-K should be funded.', -10, 1, false),
  ('educ03-opt-2', 'educ03', 'Yes—but phase in by income.', -5, 2, false),
  ('educ03-opt-3', 'educ03', 'Neutral—support targeted programs.', 0, 3, false),
  ('educ03-opt-4', 'educ03', 'No—but maintain current programs.', 5, 4, false),
  ('educ03-opt-5', 'educ03', 'No—because pre-K is a family responsibility.', 10, 5, false),
  ('educ03-skip', 'educ03', 'Not important to me', 0, 6, true),
  ('educ04-opt-1', 'educ04', 'No—because public schools need support.', -10, 1, false),
  ('educ04-opt-2', 'educ04', 'No—but allow limited options.', -5, 2, false),
  ('educ04-opt-3', 'educ04', 'Neutral—balance choice and public schools.', 0, 3, false),
  ('educ04-opt-4', 'educ04', 'Yes—but with accountability.', 5, 4, false),
  ('educ04-opt-5', 'educ04', 'Yes—because choice should expand.', 10, 5, false),
  ('educ04-skip', 'educ04', 'Not important to me', 0, 6, true),
  ('educ05-opt-1', 'educ05', 'Yes—because Pell Grants should expand.', -10, 1, false),
  ('educ05-opt-2', 'educ05', 'Yes—but target low-income students.', -5, 2, false),
  ('educ05-opt-3', 'educ05', 'Neutral—support modest increases.', 0, 3, false),
  ('educ05-opt-4', 'educ05', 'No—but maintain current levels.', 5, 4, false),
  ('educ05-opt-5', 'educ05', 'No—because aid should be reduced.', 10, 5, false),
  ('educ05-skip', 'educ05', 'Not important to me', 0, 6, true),
  ('educ06-opt-1', 'educ06', 'Yes—because testing is overused.', -10, 1, false),
  ('educ06-opt-2', 'educ06', 'Yes—but keep some accountability.', -5, 2, false),
  ('educ06-opt-3', 'educ06', 'Neutral—balance testing and flexibility.', 0, 3, false),
  ('educ06-opt-4', 'educ06', 'No—but allow alternatives.', 5, 4, false),
  ('educ06-opt-5', 'educ06', 'No—because testing ensures standards.', 10, 5, false),
  ('educ06-skip', 'educ06', 'Not important to me', 0, 6, true),
  ('educ07-opt-1', 'educ07', 'Yes—because vocational training should expand.', -10, 1, false),
  ('educ07-opt-2', 'educ07', 'Yes—but target high-demand fields.', -5, 2, false),
  ('educ07-opt-3', 'educ07', 'Neutral—support limited expansion.', 0, 3, false),
  ('educ07-opt-4', 'educ07', 'No—but maintain current funding.', 5, 4, false),
  ('educ07-opt-5', 'educ07', 'No—because training should be private.', 10, 5, false),
  ('educ07-skip', 'educ07', 'Not important to me', 0, 6, true),
  ('educ08-opt-1', 'educ08', 'Yes—because teacher pay should increase.', -10, 1, false),
  ('educ08-opt-2', 'educ08', 'Yes—but tie to performance.', -5, 2, false),
  ('educ08-opt-3', 'educ08', 'Neutral—support state-led increases.', 0, 3, false),
  ('educ08-opt-4', 'educ08', 'No—but improve working conditions.', 5, 4, false),
  ('educ08-opt-5', 'educ08', 'No—because pay is a state decision.', 10, 5, false),
  ('educ08-skip', 'educ08', 'Not important to me', 0, 6, true),
  ('educ09-opt-1', 'educ09', 'Yes—because HBCUs need strong support.', -10, 1, false),
  ('educ09-opt-2', 'educ09', 'Yes—but target critical needs.', -5, 2, false),
  ('educ09-opt-3', 'educ09', 'Neutral—support modest increases.', 0, 3, false),
  ('educ09-opt-4', 'educ09', 'No—but maintain current funding.', 5, 4, false),
  ('educ09-opt-5', 'educ09', 'No—because all schools should be treated equally.', 10, 5, false),
  ('educ09-skip', 'educ09', 'Not important to me', 0, 6, true),
  ('educ10-opt-1', 'educ10', 'Yes—because special education needs more funding.', -10, 1, false),
  ('educ10-opt-2', 'educ10', 'Yes—but target high-need districts.', -5, 2, false),
  ('educ10-opt-3', 'educ10', 'Neutral—support modest increases.', 0, 3, false),
  ('educ10-opt-4', 'educ10', 'No—but maintain current levels.', 5, 4, false),
  ('educ10-opt-5', 'educ10', 'No—because states should fund this.', 10, 5, false),
  ('educ10-skip', 'educ10', 'Not important to me', 0, 6, true);