-- Insert Emergency Management questions (10 questions, maps to 'technology' topic)
INSERT INTO questions (id, topic_id, text, is_onboarding_canonical, onboarding_slot) VALUES
  ('emer01', 'technology', 'Should FEMA funding be increased?', false, null),
  ('emer02', 'technology', 'Should federal disaster aid prioritize climate resilience upgrades?', false, null),
  ('emer03', 'technology', 'Should the government expand early warning systems for extreme weather?', false, null),
  ('emer04', 'technology', 'Should federal agencies increase support for state emergency preparedness?', false, null),
  ('emer05', 'technology', 'Should Congress streamline disaster relief approvals?', false, null),
  ('emer06', 'technology', 'Should federal law expand eligibility for disaster housing assistance?', false, null),
  ('emer07', 'technology', 'Should the government invest more in wildfire prevention?', false, null),
  ('emer08', 'technology', 'Should Congress increase funding for community disaster training?', false, null),
  ('emer09', 'technology', 'Should the federal government require stronger building codes in high-risk areas?', false, null),
  ('emer10', 'technology', 'Should disaster recovery funds prioritize low-income communities?', false, null);

INSERT INTO question_options (id, question_id, text, value, display_order, is_skip_option) VALUES
  ('emer01-opt-1', 'emer01', 'Yes—because disaster response needs major funding.', -10, 1, false),
  ('emer01-opt-2', 'emer01', 'Yes—but target high-risk areas.', -5, 2, false),
  ('emer01-opt-3', 'emer01', 'Neutral—support limited increases.', 0, 3, false),
  ('emer01-opt-4', 'emer01', 'No—but maintain current funding.', 5, 4, false),
  ('emer01-opt-5', 'emer01', 'No—because spending should be reduced.', 10, 5, false),
  ('emer01-skip', 'emer01', 'Not important to me', 0, 6, true),
  ('emer02-opt-1', 'emer02', 'Yes—because resilience must be a top priority.', -10, 1, false),
  ('emer02-opt-2', 'emer02', 'Yes—but balance with immediate relief.', -5, 2, false),
  ('emer02-opt-3', 'emer02', 'Neutral—support selective resilience upgrades.', 0, 3, false),
  ('emer02-opt-4', 'emer02', 'No—but allow optional resilience investments.', 5, 4, false),
  ('emer02-opt-5', 'emer02', 'No—because aid should be unconditional.', 10, 5, false),
  ('emer02-skip', 'emer02', 'Not important to me', 0, 6, true),
  ('emer03-opt-1', 'emer03', 'Yes—because warning systems save lives.', -10, 1, false),
  ('emer03-opt-2', 'emer03', 'Yes—but prioritize high-risk regions.', -5, 2, false),
  ('emer03-opt-3', 'emer03', 'Neutral—support targeted upgrades.', 0, 3, false),
  ('emer03-opt-4', 'emer03', 'No—but maintain current systems.', 5, 4, false),
  ('emer03-opt-5', 'emer03', 'No—because expansion is unnecessary.', 10, 5, false),
  ('emer03-skip', 'emer03', 'Not important to me', 0, 6, true),
  ('emer04-opt-1', 'emer04', 'Yes—because states need strong federal support.', -10, 1, false),
  ('emer04-opt-2', 'emer04', 'Yes—but focus on high-risk states.', -5, 2, false),
  ('emer04-opt-3', 'emer04', 'Neutral—support limited assistance.', 0, 3, false),
  ('emer04-opt-4', 'emer04', 'No—but maintain current programs.', 5, 4, false),
  ('emer04-opt-5', 'emer04', 'No—because preparedness is a state role.', 10, 5, false),
  ('emer04-skip', 'emer04', 'Not important to me', 0, 6, true),
  ('emer05-opt-1', 'emer05', 'Yes—because aid should be fast-tracked.', -10, 1, false),
  ('emer05-opt-2', 'emer05', 'Yes—but keep basic oversight.', -5, 2, false),
  ('emer05-opt-3', 'emer05', 'Neutral—support modest process improvements.', 0, 3, false),
  ('emer05-opt-4', 'emer05', 'No—but maintain current review.', 5, 4, false),
  ('emer05-opt-5', 'emer05', 'No—because strict approvals prevent waste.', 10, 5, false),
  ('emer05-skip', 'emer05', 'Not important to me', 0, 6, true),
  ('emer06-opt-1', 'emer06', 'Yes—because more families need help.', -10, 1, false),
  ('emer06-opt-2', 'emer06', 'Yes—but focus on low-income families.', -5, 2, false),
  ('emer06-opt-3', 'emer06', 'Neutral—support limited expansion.', 0, 3, false),
  ('emer06-opt-4', 'emer06', 'No—but keep current eligibility.', 5, 4, false),
  ('emer06-opt-5', 'emer06', 'No—because eligibility should be tightened.', 10, 5, false),
  ('emer06-skip', 'emer06', 'Not important to me', 0, 6, true),
  ('emer07-opt-1', 'emer07', 'Yes—because prevention is essential.', -10, 1, false),
  ('emer07-opt-2', 'emer07', 'Yes—but target high-risk regions.', -5, 2, false),
  ('emer07-opt-3', 'emer07', 'Neutral—support limited increases.', 0, 3, false),
  ('emer07-opt-4', 'emer07', 'No—but keep current funding.', 5, 4, false),
  ('emer07-opt-5', 'emer07', 'No—because prevention spending should shrink.', 10, 5, false),
  ('emer07-skip', 'emer07', 'Not important to me', 0, 6, true),
  ('emer08-opt-1', 'emer08', 'Yes—because training improves resilience.', -10, 1, false),
  ('emer08-opt-2', 'emer08', 'Yes—but focus on vulnerable areas.', -5, 2, false),
  ('emer08-opt-3', 'emer08', 'Neutral—support targeted programs.', 0, 3, false),
  ('emer08-opt-4', 'emer08', 'No—but maintain current funding.', 5, 4, false),
  ('emer08-opt-5', 'emer08', 'No—because federal training is unnecessary.', 10, 5, false),
  ('emer08-skip', 'emer08', 'Not important to me', 0, 6, true),
  ('emer09-opt-1', 'emer09', 'Yes—because national standards save lives.', -10, 1, false),
  ('emer09-opt-2', 'emer09', 'Yes—but allow phased adoption.', -5, 2, false),
  ('emer09-opt-3', 'emer09', 'Neutral—encourage states without mandates.', 0, 3, false),
  ('emer09-opt-4', 'emer09', 'No—but support voluntary improvements.', 5, 4, false),
  ('emer09-opt-5', 'emer09', 'No—because building codes are local.', 10, 5, false),
  ('emer09-skip', 'emer09', 'Not important to me', 0, 6, true),
  ('emer10-opt-1', 'emer10', 'Yes—because equity should guide recovery.', -10, 1, false),
  ('emer10-opt-2', 'emer10', 'Yes—but balance with overall need.', -5, 2, false),
  ('emer10-opt-3', 'emer10', 'Neutral—allocate based on damage severity.', 0, 3, false),
  ('emer10-opt-4', 'emer10', 'No—but ensure fair distribution.', 5, 4, false),
  ('emer10-opt-5', 'emer10', 'No—because recovery should be equal.', 10, 5, false),
  ('emer10-skip', 'emer10', 'Not important to me', 0, 6, true);

-- Insert Energy questions (10 questions, maps to 'environment' topic)
INSERT INTO questions (id, topic_id, text, is_onboarding_canonical, onboarding_slot) VALUES
  ('enrg01', 'environment', 'Should the U.S. expand renewable energy subsidies?', false, null),
  ('enrg02', 'environment', 'Should federal policy limit new oil and gas drilling leases?', false, null),
  ('enrg03', 'environment', 'Should the government invest more in nuclear energy development?', false, null),
  ('enrg04', 'environment', 'Should Congress increase incentives for energy efficiency upgrades?', false, null),
  ('enrg05', 'environment', 'Should the federal government impose stricter emissions standards on power plants?', false, null),
  ('enrg06', 'environment', 'Should the U.S. expand its strategic petroleum reserves?', false, null),
  ('enrg07', 'environment', 'Should Congress fund research in next-generation battery technology?', false, null),
  ('enrg08', 'environment', 'Should federal policy encourage energy independence over imports?', false, null),
  ('enrg09', 'environment', 'Should the government expand incentives for electric vehicles?', false, null),
  ('enrg10', 'environment', 'Should federal law limit methane emissions from energy production?', false, null);

INSERT INTO question_options (id, question_id, text, value, display_order, is_skip_option) VALUES
  ('enrg01-opt-1', 'enrg01', 'Yes—because rapid clean-energy transition is urgent.', -10, 1, false),
  ('enrg01-opt-2', 'enrg01', 'Yes—but target scalable technologies.', -5, 2, false),
  ('enrg01-opt-3', 'enrg01', 'Neutral—support limited incentives.', 0, 3, false),
  ('enrg01-opt-4', 'enrg01', 'No—but keep small, targeted subsidies.', 5, 4, false),
  ('enrg01-opt-5', 'enrg01', 'No—because subsidies should end.', 10, 5, false),
  ('enrg01-skip', 'enrg01', 'Not important to me', 0, 6, true),
  ('enrg02-opt-1', 'enrg02', 'Yes—because fossil fuel expansion should stop.', -10, 1, false),
  ('enrg02-opt-2', 'enrg02', 'Yes—but allow limited leases in low-impact areas.', -5, 2, false),
  ('enrg02-opt-3', 'enrg02', 'Neutral—limit only in sensitive areas.', 0, 3, false),
  ('enrg02-opt-4', 'enrg02', 'No—but keep basic environmental rules.', 5, 4, false),
  ('enrg02-opt-5', 'enrg02', 'No—because drilling should expand.', 10, 5, false),
  ('enrg02-skip', 'enrg02', 'Not important to me', 0, 6, true),
  ('enrg03-opt-1', 'enrg03', 'No—but prioritize renewables instead.', -10, 1, false),
  ('enrg03-opt-2', 'enrg03', 'No—but allow limited safer nuclear research.', -5, 2, false),
  ('enrg03-opt-3', 'enrg03', 'Neutral—support balanced investment.', 0, 3, false),
  ('enrg03-opt-4', 'enrg03', 'Yes—but focus on advanced reactors.', 5, 4, false),
  ('enrg03-opt-5', 'enrg03', 'Yes—because nuclear expansion is needed.', 10, 5, false),
  ('enrg03-skip', 'enrg03', 'Not important to me', 0, 6, true),
  ('enrg04-opt-1', 'enrg04', 'Yes—because efficiency reduces emissions.', -10, 1, false),
  ('enrg04-opt-2', 'enrg04', 'Yes—but target high-impact sectors.', -5, 2, false),
  ('enrg04-opt-3', 'enrg04', 'Neutral—support modest incentives.', 0, 3, false),
  ('enrg04-opt-4', 'enrg04', 'No—but maintain current incentives.', 5, 4, false),
  ('enrg04-opt-5', 'enrg04', 'No—because incentives should be reduced.', 10, 5, false),
  ('enrg04-skip', 'enrg04', 'Not important to me', 0, 6, true),
  ('enrg05-opt-1', 'enrg05', 'Yes—because strict limits are necessary.', -10, 1, false),
  ('enrg05-opt-2', 'enrg05', 'Yes—but allow phased compliance.', -5, 2, false),
  ('enrg05-opt-3', 'enrg05', 'Neutral—support moderate standards.', 0, 3, false),
  ('enrg05-opt-4', 'enrg05', 'No—but keep basic standards.', 5, 4, false),
  ('enrg05-opt-5', 'enrg05', 'No—because standards should be rolled back.', 10, 5, false),
  ('enrg05-skip', 'enrg05', 'Not important to me', 0, 6, true),
  ('enrg06-opt-1', 'enrg06', 'No—but reduce reliance on oil.', -10, 1, false),
  ('enrg06-opt-2', 'enrg06', 'No—but maintain current reserves.', -5, 2, false),
  ('enrg06-opt-3', 'enrg06', 'Neutral—support modest expansion.', 0, 3, false),
  ('enrg06-opt-4', 'enrg06', 'Yes—but keep expansion limited.', 5, 4, false),
  ('enrg06-opt-5', 'enrg06', 'Yes—because energy security requires growth.', 10, 5, false),
  ('enrg06-skip', 'enrg06', 'Not important to me', 0, 6, true),
  ('enrg07-opt-1', 'enrg07', 'Yes—because battery R&D is critical.', -10, 1, false),
  ('enrg07-opt-2', 'enrg07', 'Yes—but focus on scalable breakthroughs.', -5, 2, false),
  ('enrg07-opt-3', 'enrg07', 'Neutral—support limited research funding.', 0, 3, false),
  ('enrg07-opt-4', 'enrg07', 'No—but allow private sector leadership.', 5, 4, false),
  ('enrg07-opt-5', 'enrg07', 'No—because federal R&D should shrink.', 10, 5, false),
  ('enrg07-skip', 'enrg07', 'Not important to me', 0, 6, true),
  ('enrg08-opt-1', 'enrg08', 'No—but prioritize global clean-energy cooperation.', -10, 1, false),
  ('enrg08-opt-2', 'enrg08', 'No—but balance independence with trade.', -5, 2, false),
  ('enrg08-opt-3', 'enrg08', 'Neutral—support flexible sourcing.', 0, 3, false),
  ('enrg08-opt-4', 'enrg08', 'Yes—but avoid excessive protectionism.', 5, 4, false),
  ('enrg08-opt-5', 'enrg08', 'Yes—because independence should be top priority.', 10, 5, false),
  ('enrg08-skip', 'enrg08', 'Not important to me', 0, 6, true),
  ('enrg09-opt-1', 'enrg09', 'Yes—because EV adoption should accelerate.', -10, 1, false),
  ('enrg09-opt-2', 'enrg09', 'Yes—but target incentives to middle-income buyers.', -5, 2, false),
  ('enrg09-opt-3', 'enrg09', 'Neutral—support limited incentives.', 0, 3, false),
  ('enrg09-opt-4', 'enrg09', 'No—but keep minimal incentives.', 5, 4, false),
  ('enrg09-opt-5', 'enrg09', 'No—because incentives should end.', 10, 5, false),
  ('enrg09-skip', 'enrg09', 'Not important to me', 0, 6, true),
  ('enrg10-opt-1', 'enrg10', 'Yes—because methane cuts are urgent.', -10, 1, false),
  ('enrg10-opt-2', 'enrg10', 'Yes—but allow flexible compliance.', -5, 2, false),
  ('enrg10-opt-3', 'enrg10', 'Neutral—support moderate standards.', 0, 3, false),
  ('enrg10-opt-4', 'enrg10', 'No—but keep minimal limits.', 5, 4, false),
  ('enrg10-opt-5', 'enrg10', 'No—because regulation should be reduced.', 10, 5, false),
  ('enrg10-skip', 'enrg10', 'Not important to me', 0, 6, true);