-- Insert Commerce questions (10 questions, maps to 'economy' topic)
INSERT INTO questions (id, topic_id, text, is_onboarding_canonical, onboarding_slot) VALUES
  ('comm01', 'economy', 'Should the federal government increase regulation of large corporations?', false, null),
  ('comm02', 'economy', 'Should antitrust enforcement be strengthened?', false, null),
  ('comm03', 'economy', 'Should the U.S. impose stricter rules on mergers and acquisitions?', false, null),
  ('comm04', 'economy', 'Should the government expand consumer protection regulations?', false, null),
  ('comm05', 'economy', 'Should federal law require more corporate transparency?', false, null),
  ('comm06', 'economy', 'Should Congress regulate data brokers more strictly?', false, null),
  ('comm07', 'economy', 'Should the government support small business lending programs?', false, null),
  ('comm08', 'economy', 'Should federal agencies increase oversight of e-commerce platforms?', false, null),
  ('comm09', 'economy', 'Should Congress expand protections for franchisees?', false, null),
  ('comm10', 'economy', 'Should the government limit corporate stock buybacks?', false, null);

INSERT INTO question_options (id, question_id, text, value, display_order, is_skip_option) VALUES
  ('comm01-opt-1', 'comm01', 'Yes—because stronger oversight is needed.', -10, 1, false),
  ('comm01-opt-2', 'comm01', 'Yes—but target the largest firms.', -5, 2, false),
  ('comm01-opt-3', 'comm01', 'Neutral—regulate where harms are clear.', 0, 3, false),
  ('comm01-opt-4', 'comm01', 'No—but keep basic protections.', 5, 4, false),
  ('comm01-opt-5', 'comm01', 'No—because regulation should be reduced.', 10, 5, false),
  ('comm01-skip', 'comm01', 'Not important to me', 0, 6, true),
  ('comm02-opt-1', 'comm02', 'Yes—because monopolies must be broken up.', -10, 1, false),
  ('comm02-opt-2', 'comm02', 'Yes—but focus on major abuses.', -5, 2, false),
  ('comm02-opt-3', 'comm02', 'Neutral—enforce current rules with minor updates.', 0, 3, false),
  ('comm02-opt-4', 'comm02', 'No—but keep current enforcement.', 5, 4, false),
  ('comm02-opt-5', 'comm02', 'No—because enforcement should be reduced.', 10, 5, false),
  ('comm02-skip', 'comm02', 'Not important to me', 0, 6, true),
  ('comm03-opt-1', 'comm03', 'Yes—because consolidation should be limited.', -10, 1, false),
  ('comm03-opt-2', 'comm03', 'Yes—but focus on harmful deals.', -5, 2, false),
  ('comm03-opt-3', 'comm03', 'Neutral—review mergers case-by-case.', 0, 3, false),
  ('comm03-opt-4', 'comm03', 'No—but maintain current rules.', 5, 4, false),
  ('comm03-opt-5', 'comm03', 'No—because markets should consolidate freely.', 10, 5, false),
  ('comm03-skip', 'comm03', 'Not important to me', 0, 6, true),
  ('comm04-opt-1', 'comm04', 'Yes—because consumer protections should expand.', -10, 1, false),
  ('comm04-opt-2', 'comm04', 'Yes—but target high-risk industries.', -5, 2, false),
  ('comm04-opt-3', 'comm04', 'Neutral—support targeted protections.', 0, 3, false),
  ('comm04-opt-4', 'comm04', 'No—but keep current protections.', 5, 4, false),
  ('comm04-opt-5', 'comm04', 'No—because regulation should be reduced.', 10, 5, false),
  ('comm04-skip', 'comm04', 'Not important to me', 0, 6, true),
  ('comm05-opt-1', 'comm05', 'Yes—because transparency should be mandatory.', -10, 1, false),
  ('comm05-opt-2', 'comm05', 'Yes—but focus on major corporations.', -5, 2, false),
  ('comm05-opt-3', 'comm05', 'Neutral—support targeted disclosure.', 0, 3, false),
  ('comm05-opt-4', 'comm05', 'No—but keep current rules.', 5, 4, false),
  ('comm05-opt-5', 'comm05', 'No—because mandates are burdensome.', 10, 5, false),
  ('comm05-skip', 'comm05', 'Not important to me', 0, 6, true),
  ('comm06-opt-1', 'comm06', 'Yes—because data brokers should face strict limits.', -10, 1, false),
  ('comm06-opt-2', 'comm06', 'Yes—but allow legitimate uses.', -5, 2, false),
  ('comm06-opt-3', 'comm06', 'Neutral—support targeted regulation.', 0, 3, false),
  ('comm06-opt-4', 'comm06', 'No—but require transparency.', 5, 4, false),
  ('comm06-opt-5', 'comm06', 'No—because regulation is unnecessary.', 10, 5, false),
  ('comm06-skip', 'comm06', 'Not important to me', 0, 6, true),
  ('comm07-opt-1', 'comm07', 'Yes—because small businesses need support.', -10, 1, false),
  ('comm07-opt-2', 'comm07', 'Yes—but target underserved areas.', -5, 2, false),
  ('comm07-opt-3', 'comm07', 'Neutral—support limited programs.', 0, 3, false),
  ('comm07-opt-4', 'comm07', 'No—but maintain current programs.', 5, 4, false),
  ('comm07-opt-5', 'comm07', 'No—because lending should be private.', 10, 5, false),
  ('comm07-skip', 'comm07', 'Not important to me', 0, 6, true),
  ('comm08-opt-1', 'comm08', 'Yes—because platforms need strong oversight.', -10, 1, false),
  ('comm08-opt-2', 'comm08', 'Yes—but focus on major platforms.', -5, 2, false),
  ('comm08-opt-3', 'comm08', 'Neutral—support targeted oversight.', 0, 3, false),
  ('comm08-opt-4', 'comm08', 'No—but require basic transparency.', 5, 4, false),
  ('comm08-opt-5', 'comm08', 'No—because oversight is unnecessary.', 10, 5, false),
  ('comm08-skip', 'comm08', 'Not important to me', 0, 6, true),
  ('comm09-opt-1', 'comm09', 'Yes—because franchisees need strong protections.', -10, 1, false),
  ('comm09-opt-2', 'comm09', 'Yes—but balance with franchisor rights.', -5, 2, false),
  ('comm09-opt-3', 'comm09', 'Neutral—support targeted protections.', 0, 3, false),
  ('comm09-opt-4', 'comm09', 'No—but keep current rules.', 5, 4, false),
  ('comm09-opt-5', 'comm09', 'No—because regulation is unnecessary.', 10, 5, false),
  ('comm09-skip', 'comm09', 'Not important to me', 0, 6, true),
  ('comm10-opt-1', 'comm10', 'Yes—because buybacks should be limited.', -10, 1, false),
  ('comm10-opt-2', 'comm10', 'Yes—but allow some flexibility.', -5, 2, false),
  ('comm10-opt-3', 'comm10', 'Neutral—support targeted limits.', 0, 3, false),
  ('comm10-opt-4', 'comm10', 'No—but require disclosure.', 5, 4, false),
  ('comm10-opt-5', 'comm10', 'No—because corporations should decide.', 10, 5, false),
  ('comm10-skip', 'comm10', 'Not important to me', 0, 6, true);