// audit-answer-sources
// Per-answer, evidence-grounded score-inversion auditor (see docs/score-inversion-fix.md →
// "Per-answer source audit"). The AI-CHECK stage of a detect → AI-verify → targeted-fix loop.
//
// The cheap SQL PREFILTER (public.answer_audit_detect) enqueues, into answer_source_audit,
// individual CITED answers whose L/R direction is OPPOSITE the candidate's party — but party-
// opposite is NOT proof of a wrong answer. This function takes a bounded batch of those
// `pending` rows and, for EACH one, asks Gemini whether the cited source (source_description +
// the source_url content) tells the SAME story as the stored answer_value, and whether the
// source_url is reachable/real. It writes a verdict ∈ {consistent, contradicts, unverifiable}.
//
// Only `contradicts` rows are later regenerated by public.answer_audit_fix (targeted delete +
// generate-legislator-answers). Everything else is left untouched. This function never deletes
// or modifies candidate_answers.
//
// Requires: GOOGLE_AI_API_KEY secret in Supabase Vault (same as generate-legislator-answers).
// Trigger:  POST /functions/v1/audit-answer-sources  (cron x-cron-secret / service-role / admin)
// Body:     { limit? }   limit: cap rows checked this run (default + hard ceiling below)
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { isCronAuthorized } from "../_shared/cron-auth.ts";
import {
  parseVerdict,
  combineReachability,
  isSafePublicHttpUrl,
  type AuditVerdict,
} from "../_shared/answer-source-audit.ts";

// Background-task escape hatch: lets the handler return before the (slow, Gemini-bound) batch
// finishes, so a caller with a short timeout (pg_net's default is 5s) doesn't abandon/abort the
// run before any verdict is written. See the handler for why this matters.
declare const EdgeRuntime: { waitUntil: (promise: Promise<unknown>) => void };

const GOOGLE_AI_KEY = Deno.env.get('GOOGLE_AI_API_KEY');
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const SUPABASE_ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')!;

const GEMINI_MODEL = 'gemini-2.5-flash';
const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta';

const DEFAULT_BATCH = 20;
const MAX_BATCH = 20;            // hard ceiling: one Gemini call per row, keep spend bounded
const DELAY_MS = 1500;           // gentle pacing between Gemini calls
const REACH_TIMEOUT_MS = 8000;   // per-URL reachability probe budget

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const delay = (ms: number) => new Promise((r) => setTimeout(r, ms));

// ── Types ─────────────────────────────────────────────────────────────────────

interface AuditRow {
  candidate_id: string;
  question_id: string;
  answer_value: number;
  attempts: number;
}

interface JoinedAnswer extends AuditRow {
  question_text: string;
  source_description: string | null;
  source_url: string | null;
}

// ── Source reachability probe (timeout-guarded) ─────────────────────────────────

async function isReachable(url: string | null): Promise<boolean> {
  // SSRF guard: only probe public http(s) hosts — never loopback/link-local/private ranges.
  // (A blocked URL just reads as "unreachable"; it can only ever yield the non-destructive
  // 'unverifiable' on its own — 'contradicts' still requires the AI's actual reading.)
  if (!isSafePublicHttpUrl(url)) return false;
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), REACH_TIMEOUT_MS);
  try {
    // HEAD first (cheap); some servers reject HEAD, so fall back to a ranged GET.
    let res = await fetch(url, { method: 'HEAD', redirect: 'follow', signal: ctrl.signal });
    if (res.status === 405 || res.status === 403 || res.status === 501) {
      res = await fetch(url, {
        method: 'GET',
        redirect: 'follow',
        signal: ctrl.signal,
        headers: { Range: 'bytes=0-0' },
      });
    }
    return res.status < 400;
  } catch {
    return false;
  } finally {
    clearTimeout(t);
  }
}

// ── Gemini stance check ─────────────────────────────────────────────────────────

function extractJson(text: string): Record<string, unknown> | null {
  try { return JSON.parse(text); } catch { /* fall through */ }
  const fence = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fence) { try { return JSON.parse(fence[1]); } catch { /* fall through */ } }
  const brace = text.match(/(\{[\s\S]*\})/);
  if (brace) { try { return JSON.parse(brace[1]); } catch { /* fall through */ } }
  return null;
}

// Ask Gemini whether the cited evidence supports the stored direction. Returns the raw parsed
// verdict; reachability is folded in by the caller via combineReachability.
async function checkStance(a: JoinedAnswer): Promise<{ verdict: AuditVerdict; reason: string }> {
  const direction =
    a.answer_value > 0 ? 'SUPPORTS (positive / agrees with)'
      : a.answer_value < 0 ? 'OPPOSES (negative / disagrees with)'
      : 'is NEUTRAL on';

  // Bounded prompt: trim the (already <=1000 char) evidence prose defensively.
  const evidence = (a.source_description ?? '').slice(0, 1000) || '(no evidence prose stored)';
  const sourceUrl = a.source_url ?? '(none)';

  const prompt =
`You are auditing one stored policy position for accuracy against its OWN cited source.

QUESTION: ${a.question_text}

STORED POSITION: the record says this politician ${direction} the question above
(numeric value ${a.answer_value} on a -10 oppose … +10 support scale).

CITED EVIDENCE PROSE: ${evidence}
CITED SOURCE URL: ${sourceUrl}

Using web search to read the cited source URL (and judge whether it is a real, reachable page
about this politician), decide whether the SOURCE tells the SAME story as the STORED POSITION.

Return ONLY a JSON object:
{
  "verdict": "<consistent | contradicts | unverifiable>",
  "reason": "<one short sentence, <= 300 chars>"
}

Rules:
- "consistent": the source clearly supports the stored direction (same sign of stance).
- "contradicts": the source clearly shows the OPPOSITE direction to the stored value, OR the
  cited URL is fabricated / about someone else / does not support the claim at all.
- "unverifiable": you cannot reach or confirm the source and the prose alone is inconclusive.
- Judge DIRECTION (support vs oppose), not intensity. Do not penalize a small magnitude gap.`;

  const body = {
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    tools: [{ googleSearch: {} }],
    generationConfig: { temperature: 0.1, maxOutputTokens: 1024 },
  };

  const res = await fetch(
    `${GEMINI_API_BASE}/models/${GEMINI_MODEL}:generateContent?key=${GOOGLE_AI_KEY}`,
    { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) },
  );

  if (!res.ok) {
    const msg = await res.text();
    throw new Error(`Gemini ${res.status}: ${msg.slice(0, 300)}`);
  }

  const data = await res.json();
  const text: string = data?.candidates?.[0]?.content?.parts?.[0]?.text ?? '';
  const parsed = extractJson(text);
  // parseVerdict tolerates both the JSON object and a bare prose fallback, and defaults to
  // 'unverifiable' (the safe, non-destructive verdict) when it cannot classify.
  return parseVerdict(parsed ?? text);
}

// ── Batch processor ──────────────────────────────────────────────────────────────

async function auditBatch(
  supabase: ReturnType<typeof createClient>,
  rows: JoinedAnswer[],
): Promise<Array<Record<string, unknown>>> {
  const results: Array<Record<string, unknown>> = [];

  for (const a of rows) {
    let verdict: AuditVerdict = 'unverifiable';
    let reason = 'not checked';
    try {
      const [ai, reachable] = await Promise.all([
        checkStance(a),
        isReachable(a.source_url),
      ]);
      const combined = combineReachability(ai, reachable);
      verdict = combined.verdict;
      reason = combined.reason;
    } catch (e) {
      // A Gemini/network error leaves the row 'unverifiable' (with bumped attempts) so the
      // attempts cap eventually parks it rather than retrying forever.
      verdict = 'unverifiable';
      reason = `check error: ${String(e)}`.slice(0, 500);
      console.error(`[audit] ${a.candidate_id}/${a.question_id}:`, e);
    }

    const { error: updErr } = await supabase
      .from('answer_source_audit')
      .update({
        verdict,
        reason,
        checked_at: new Date().toISOString(),
        attempts: (a.attempts ?? 0) + 1,
        updated_at: new Date().toISOString(),
      })
      .eq('candidate_id', a.candidate_id)
      .eq('question_id', a.question_id);
    if (updErr) console.error('[audit] update failed:', updErr.message);

    results.push({ candidate_id: a.candidate_id, question_id: a.question_id, verdict });
    await delay(DELAY_MS);
  }

  return results;
}

// ── Request handler ───────────────────────────────────────────────────────────

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });

  const json = (b: unknown, status = 200) =>
    new Response(JSON.stringify(b), {
      status,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  try {
    const token = (req.headers.get('Authorization') ?? '').replace('Bearer ', '');
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

    // Auth: cron x-cron-secret / service-role bearer (server-side) OR an admin user profile.
    if (!(await isCronAuthorized(req))) {
      const { data: { user }, error: authErr } =
        await createClient(SUPABASE_URL, SUPABASE_ANON_KEY).auth.getUser(token);
      if (authErr || !user) return json({ error: 'Unauthorized' }, 401);
      // Admin check via the repo's single source of truth: user_roles/app_role through the
      // has_role SECURITY DEFINER RPC (the `profiles` table has no `role` column — checking it
      // would wrongly 403 every real admin, and would be self-promotable if one were ever added).
      const { data: isAdmin } = await supabase.rpc('has_role', { _user_id: user.id, _role: 'admin' });
      if (!isAdmin) return json({ error: 'Forbidden' }, 403);
    }

    // Kill-switch (default OFF). No-op silently so a scheduled run is inert until enabled.
    const { data: sw } = await supabase
      .from('admin_stats_cache')
      .select('stat_value')
      .eq('stat_key', 'answer_audit_enabled')
      .maybeSingle();
    const enabled = (sw?.stat_value as { enabled?: boolean } | null)?.enabled === true;
    if (!enabled) return json({ skipped: 'disabled' });

    if (!GOOGLE_AI_KEY) return json({ error: 'GOOGLE_AI_API_KEY not configured' }, 500);

    const reqBody = await req.json().catch(() => ({})) as Record<string, unknown>;
    const limit = Math.min(MAX_BATCH, Math.max(1, Number(reqBody.limit ?? DEFAULT_BATCH)));

    // Bounded batch of pending rows.
    const { data: pending, error: qErr } = await supabase
      .from('answer_source_audit')
      .select('candidate_id, question_id, answer_value, attempts')
      .eq('verdict', 'pending')
      .order('created_at', { ascending: true })
      .limit(limit);
    if (qErr) return json({ error: qErr.message }, 500);
    if (!pending || pending.length === 0) return json({ done: true, checked: 0 });

    // Join the stored answer's evidence + the question text. One query per dimension keeps the
    // PostgREST surface simple; both are keyed on the same candidate/question pairs.
    const qIds = [...new Set(pending.map((r) => r.question_id as string))];
    const cIds = [...new Set(pending.map((r) => r.candidate_id as string))];
    const [{ data: questions }, { data: answers }] = await Promise.all([
      supabase.from('questions').select('id, text').in('id', qIds),
      supabase
        .from('candidate_answers')
        .select('candidate_id, question_id, source_description, source_url')
        .in('candidate_id', cIds)
        .in('question_id', qIds),
    ]);

    const qText = new Map((questions ?? []).map((q) => [q.id as string, q.text as string]));
    const ansKey = (c: string, q: string) => `${c}::${q}`;
    const ansMap = new Map(
      (answers ?? []).map((a) => [
        ansKey(a.candidate_id as string, a.question_id as string),
        a,
      ]),
    );

    const joined: JoinedAnswer[] = [];
    for (const r of pending) {
      const cid = r.candidate_id as string;
      const qid = r.question_id as string;
      const ans = ansMap.get(ansKey(cid, qid));
      // If the underlying answer is gone (already regenerated/deleted), mark it consistent so
      // it drops out of the pending pool rather than being checked against nothing.
      if (!ans) {
        await supabase
          .from('answer_source_audit')
          .update({
            verdict: 'consistent',
            reason: 'underlying answer no longer present',
            checked_at: new Date().toISOString(),
            attempts: (r.attempts as number ?? 0) + 1,
            updated_at: new Date().toISOString(),
          })
          .eq('candidate_id', cid)
          .eq('question_id', qid);
        continue;
      }
      joined.push({
        candidate_id: cid,
        question_id: qid,
        answer_value: r.answer_value as number,
        attempts: r.attempts as number,
        question_text: qText.get(qid) ?? '(question text unavailable)',
        source_description: (ans.source_description as string | null) ?? null,
        source_url: (ans.source_url as string | null) ?? null,
      });
    }

    // Run the batch in the background and return immediately. Each verdict is written to
    // answer_source_audit as it completes, so a run that outlives the caller's timeout (the cron
    // fires this via pg_net with a ~5s default) still persists every row it finished, and the next
    // scheduled run resumes the remaining 'pending' rows. Mirrors generate-legislator-answers.
    EdgeRuntime.waitUntil(auditBatch(supabase, joined));
    return json({ started: true, queued: joined.length });
  } catch (e) {
    console.error('[audit-answer-sources]', e);
    return json({ error: String(e) }, 500);
  }
});
