// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check if we're in a browser environment
const isBrowser = typeof window !== 'undefined' && typeof localStorage !== 'undefined';

// Create Supabase client with graceful handling for SSR/test contexts
function createSupabaseClient(): SupabaseClient<Database> {
  // Validate required environment variables
  if (!SUPABASE_URL || typeof SUPABASE_URL !== 'string') {
    if (isBrowser) {
      throw new Error(
        'Missing VITE_SUPABASE_URL environment variable. ' +
        'Please ensure your .env file contains VITE_SUPABASE_URL with your Supabase project URL.'
      );
    }
    // Non-browser context: warn and return a stub
    console.warn('Supabase client not initialized - missing VITE_SUPABASE_URL or not in browser');
    return null as unknown as SupabaseClient<Database>;
  }

  if (!SUPABASE_PUBLISHABLE_KEY || typeof SUPABASE_PUBLISHABLE_KEY !== 'string') {
    if (isBrowser) {
      throw new Error(
        'Missing VITE_SUPABASE_PUBLISHABLE_KEY environment variable. ' +
        'Please ensure your .env file contains VITE_SUPABASE_PUBLISHABLE_KEY with your Supabase anon key.'
      );
    }
    // Non-browser context: warn and return a stub
    console.warn('Supabase client not initialized - missing VITE_SUPABASE_PUBLISHABLE_KEY or not in browser');
    return null as unknown as SupabaseClient<Database>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: isBrowser ? localStorage : undefined,
      persistSession: isBrowser,
      autoRefreshToken: isBrowser,
    }
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createSupabaseClient();